
package gui;

import Conex.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

public class Admin_Registro_Trabajos extends javax.swing.JFrame {

    private DefaultTableModel reg;
    public Admin_Registro_Trabajos() {
        initComponents();
        tblPed.setBorder(new LineBorder(new Color(0, 0, 0)));
	tblPed.setFillsViewportHeight(true);
        listar_Registro_Trabajos();
    }
    
    private double Calculo(String s,double peso,int cantidad){
        switch (s) {
            case "ORO":
                return peso*(3.68)*45*cantidad;
            case "PLATA":
                return peso*7*cantidad;
            default:
                return peso*4.5*cantidad;
        }
    }
    
    void listar_Registro_Trabajos(){
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        
        reg=new DefaultTableModel();
        reg.addColumn("Nº de Boleta");
        reg.addColumn("ID Artículo");
        reg.addColumn("Medida");
        reg.addColumn("Cantidad");
        reg.addColumn("Material");
        reg.addColumn("Peso");
        reg.addColumn("Monto Total");
        reg.addColumn("Estado");
        tblPed.setModel(reg);
        
        
        String sql = "SELECT * FROM articulo_pedido";
        
        String []datos = new String[8];
        try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                
               String sentencia_buscar_Articulo = ("SELECT SOLICITUD, ID, DIRECCION_CASA, ESTADO from DIRECCION WHERE SOLICITUD = '"+rs.getString(2)+"'");
               PreparedStatement pstArticulo = cn.prepareStatement(sentencia_buscar_Articulo);

               ResultSet resultado_articulo = pstArticulo.executeQuery();

               if(resultado_articulo.next()){
                   datos[1] =resultado_articulo.getString("ID");
               }                         
                
                datos[2] = rs.getString(3);
                datos[3] = ""+rs.getInt(7);
                datos[4] = rs.getString(4);
                datos[5] = ""+rs.getDouble(5);
                datos[6] = ""+Calculo(rs.getString(4), rs.getDouble(5), rs.getInt(7));
                datos[7] = rs.getString(10);
                
                reg.addRow(datos);
            }
            tblPed.setModel(reg);
        }catch(SQLException ex){
            mensaje("No se pudo conectar con la Base de Datos");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPed = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRO DE TRABAJOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 16, 350, -1));

        jLabel2.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("<html>A continuación se muestra el registro de trabajos que se encuentran en el sistema.</html>");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 520, -1));

        tblPed.setBackground(new java.awt.Color(255, 153, 153));
        tblPed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        tblPed.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        tblPed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblPed.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblPed);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 76, 713, 250));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/off.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 90, 40));

        lblFondo1.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/fondo_rosa.png.jpg"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        Ventana_Administrador va = new Ventana_Administrador();
        va.setLocationRelativeTo(null);
        va.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Registro_Trabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Registro_Trabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Registro_Trabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Registro_Trabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Registro_Trabajos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JTable tblPed;
    // End of variables declaration//GEN-END:variables
}
