/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Calcular_Presupuesto extends javax.swing.JFrame {

    /**
     * Creates new form Calcular_Presupuesto
     */
    public Calcular_Presupuesto() {
        initComponents();
        ImageIcon imagen = new ImageIcon("src/imagenes_interfaces/logo_creoxd.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblIcono.getWidth()-1, lblIcono.getHeight()-1, Image.SCALE_DEFAULT));
        lblIcono.setIcon(icono);
        
        btnCalcular.setIcon(setIcono("/imagenes_complementarias/dinero.png", btnCalcular));
        btnCalcular.setPressedIcon(setIconoPresionado("/imagenes_complementarias/dinero.png", btnCalcular, 4, 4));
        btnRetro.setIcon(setIcono("/imagenes_interfaces/retroceder.png", btnRetro));
        btnRetro.setPressedIcon(setIconoPresionado("/imagenes_interfaces/retroceder.png", btnRetro, 9, 9));
        btnConfirmar.setIcon(setIcono("/imagenes_complementarias/confirmar.png", btnConfirmar));
        btnConfirmar.setPressedIcon(setIconoPresionado("/imagenes_complementarias/confirmar.png", btnConfirmar, 9, 9));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comBox = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnRetro = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFondo1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel1.setText("CALCULAR PRESUPUESTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 20));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setText("Peso (gr.) : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel3.setText("Material:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel5.setText("Monto total calculado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        comBox.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        comBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ORO", "PLATA", "BRONCE" }));
        getContentPane().add(comBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 93, 30));
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 93, -1));

        txtTotal.setEditable(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 83, -1));

        btnConfirmar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConfirmar.setContentAreaFilled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 80, 70));

        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel7.setText("<html>Esta ventana es para calcular el monto total aproximado del artículo a fabricar. Si desea puede saltarse esta ventana y seleccionar \"Confirmar Solicitud\"</html>");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 53, 300, 60));

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCalcular.setBorder(null);
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 80, 80));

        btnRetro.setContentAreaFilled(false);
        btnRetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, 40));
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 100, 100));

        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel6.setText("Calcular");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        lblFondo1.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/color_ventanas.jpg"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        dispose();
        Registrar_Direccion rd=new Registrar_Direccion();
        rd.setLocationRelativeTo(null);
        rd.setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try{
            double peso=Double.parseDouble(txtPeso.getText());
            String material=comBox.getSelectedItem().toString().trim();
            double total=Calculo(material, peso);
            txtTotal.setText(String.format("%.2f",total));
        }catch(Exception e){
            mensaje("PESO INVÁLIDO");
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnRetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetroActionPerformed
        int r = JOptionPane.showConfirmDialog(null, "¿Está seguro de cancelar su solicitud?");
        if(r==0){
        dispose();
        Inicio_invitado ii=new Inicio_invitado();
        ii.setLocationRelativeTo(null);
        ii.setVisible(true);
        mensaje("REGISTRO DE SOLICITUD CANCELADA");
        }
    }//GEN-LAST:event_btnRetroActionPerformed
    
    private double Calculo(String s,double peso){
        switch (s) {
            case "ORO":
                return peso*(3.68)*45;
            case "PLATA":
                return peso*7;
            default:
                return peso*4.5;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcular_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcular_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcular_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcular_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcular_Presupuesto().setVisible(true);
            }
        });
    }
    
    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = boton.getWidth() - 6;
        int alto = boton.getHeight() - 6;
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth()-ancho;
        int height = boton.getHeight()-altura;
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRetro;
    private javax.swing.JComboBox<String> comBox;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
