/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author SAMIR
 */
public class ClienteCatalogo_A extends javax.swing.JFrame {

    ButtonGroup grupoDeradios;
    /**
     * Creates new form ClienteCatalogo_A
     */
    public ClienteCatalogo_A() {
        initComponents();
        FuncionIcono("src/imagenes/A0001.jpg", lblA1);
        FuncionIcono("src/imagenes/A0002.jpg", lblA2);
        FuncionIcono("src/imagenes/A0003.jpg", lblA3);
        FuncionIcono("src/imagenes/A0004.jpg", lblA4);
        FuncionIcono("src/imagenes/A0005.jpg", lblA5);
        FuncionIcono("src/imagenes/A0006.jpg", lblA6);
        
        grupoDeradios = new ButtonGroup();
        
        grupoDeradios.add(a1);
        grupoDeradios.add(a2);
        grupoDeradios.add(a3);
        grupoDeradios.add(a4);
        grupoDeradios.add(a6);
        grupoDeradios.add(a5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        a1 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        a4 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        a6 = new javax.swing.JRadioButton();
        lblA2 = new javax.swing.JLabel();
        lblA1 = new javax.swing.JLabel();
        lblA4 = new javax.swing.JLabel();
        a5 = new javax.swing.JRadioButton();
        lblA6 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        boton = new javax.swing.JButton();
        lblA5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CATALOGO DE ARTICULOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, 253, 25));

        jLabel2.setText("Seleccione el artículo de su agrado.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 51, 322, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 78, 426, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 117, 426, -1));

        a1.setText("A0001");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 276, -1, -1));

        a3.setText("A0003");
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 456, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setText("SECCION ARETES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 86, -1, -1));

        a4.setText("A0004");
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 456, -1, -1));

        a2.setText("A0002");
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 276, -1, -1));

        a6.setText("A0006");
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 639, -1, -1));
        getContentPane().add(lblA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 145, 110, 113));
        getContentPane().add(lblA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 145, 110, 113));
        getContentPane().add(lblA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 325, 110, 113));

        a5.setText("A0005");
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 639, -1, -1));
        getContentPane().add(lblA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 510, 110, 113));
        getContentPane().add(lblA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 325, 110, 113));

        jButton1.setText("Regresar página");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 699, -1, -1));

        boton.setText("Seleccionar");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 699, -1, -1));
        getContentPane().add(lblA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 510, 110, 113));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 685, 438, -1));

        lblFondo1.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_catalogo.jpg"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        ClienteCatalogo_P ccp = new ClienteCatalogo_P();
        ccp.setLocationRelativeTo(null);
        ccp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        if(evt.getSource() == boton){
            valideRadios();
        }
    }//GEN-LAST:event_botonActionPerformed

    private void valideRadios(){
        if(a1.isSelected()){
            cad_A="A0001";
            Seleccionar(cad_A);
        }
        else if(a2.isSelected()){
            cad_A="A0002";
            Seleccionar(cad_A);
        }
        else if(a3.isSelected()){
            cad_A="A0003";
            Seleccionar(cad_A);
        }
        else if(a4.isSelected()){
            cad_A="A0004";
            Seleccionar(cad_A);
        }
        else if(a5.isSelected()){
            cad_A="A0005";
            Seleccionar(cad_A);
        }
        else if(a6.isSelected()){
            cad_A="A0006";
            Seleccionar(cad_A);
        }else{
            JOptionPane.showMessageDialog(this,"SELECCIONE UN ARTÍCULO");
        }
    }
    
    public static String cad_A=null;
    public void Seleccionar(String s){
        int r = JOptionPane.showConfirmDialog(null, "¿Está seguro de escoger el artículo "+s+"?");
        if(r==0){
            dispose();
            Calcular_Presupuesto cp=new Calcular_Presupuesto();
            cp.setLocationRelativeTo(null);
            cp.setVisible(true);
            
        }else{
            grupoDeradios.clearSelection();
        }
    }
    public void FuncionIcono(String s, JLabel lbl){
        ImageIcon imagen = new ImageIcon(s);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(icono);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteCatalogo_A().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a6;
    private javax.swing.JButton boton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblA4;
    private javax.swing.JLabel lblA5;
    private javax.swing.JLabel lblA6;
    private javax.swing.JLabel lblFondo1;
    // End of variables declaration//GEN-END:variables
}
