/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SAMIR
 */
public final class ClienteCatalogo_P extends javax.swing.JFrame {

    ButtonGroup grupoDeradios;
    /**
     * Creates new form ClienteCatalogo_P
     */
    public ClienteCatalogo_P() {
        initComponents();
        
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes_complementarias/bicho_izq.jpg")));
        
        grupoDeradios = new ButtonGroup();
        
        grupoDeradios.add(p1);
        grupoDeradios.add(p2);
        grupoDeradios.add(p3);
        grupoDeradios.add(p4);
        grupoDeradios.add(p5);
        grupoDeradios.add(p6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRetro = new javax.swing.JButton();
        btnRetro1 = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        boton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        p6 = new javax.swing.JRadioButton();
        p5 = new javax.swing.JRadioButton();
        p4 = new javax.swing.JRadioButton();
        p3 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        p1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CATALOGO DE ARTICULOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 19, 350, 25));

        jLabel2.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione el artículo de su agrado.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 50, 322, -1));

        btnRetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/atras_ventana.png"))); // NOI18N
        btnRetro.setContentAreaFilled(false);
        btnRetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 70, 70));

        btnRetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/sgte.png"))); // NOI18N
        btnRetro1.setContentAreaFilled(false);
        btnRetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetro1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 70, 70));

        lblImagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 190, 180));

        boton.setBackground(new java.awt.Color(255, 204, 153));
        boton.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        boton.setForeground(new java.awt.Color(0, 0, 0));
        boton.setText("Seleccionar");
        boton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 100, 30));

        jPanel3.setBackground(new java.awt.Color(248, 231, 215));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p6.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        p6.setForeground(new java.awt.Color(0, 0, 0));
        p6.setText("P0006");
        p6.setContentAreaFilled(false);
        p6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                p6ItemStateChanged(evt);
            }
        });
        jPanel3.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, -1));

        p5.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        p5.setForeground(new java.awt.Color(0, 0, 0));
        p5.setText("P0005");
        p5.setContentAreaFilled(false);
        p5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                p5ItemStateChanged(evt);
            }
        });
        jPanel3.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, -1));

        p4.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        p4.setForeground(new java.awt.Color(0, 0, 0));
        p4.setText("P0004");
        p4.setContentAreaFilled(false);
        p4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                p4ItemStateChanged(evt);
            }
        });
        jPanel3.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, -1));

        p3.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        p3.setForeground(new java.awt.Color(0, 0, 0));
        p3.setText("P0003");
        p3.setContentAreaFilled(false);
        p3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                p3ItemStateChanged(evt);
            }
        });
        jPanel3.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, -1));

        p2.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        p2.setForeground(new java.awt.Color(0, 0, 0));
        p2.setText("P0002");
        p2.setContentAreaFilled(false);
        p2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                p2ItemStateChanged(evt);
            }
        });
        jPanel3.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, -1));

        p1.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        p1.setForeground(new java.awt.Color(0, 0, 0));
        p1.setText("P0001");
        p1.setContentAreaFilled(false);
        p1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                p1ItemStateChanged(evt);
            }
        });
        jPanel3.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, -1));

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Sección Pulseras");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 160, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 310, 260));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/fondo_piel_aux.jpg"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetroActionPerformed
        dispose();
        ClienteCatalogo_C ccc = new ClienteCatalogo_C();
        ccc.setLocationRelativeTo(null);
        ccc.setVisible(true);
    }//GEN-LAST:event_btnRetroActionPerformed

    private void btnRetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetro1ActionPerformed
         dispose();
        ClienteCatalogo_A cca = new ClienteCatalogo_A();
        cca.setLocationRelativeTo(null);
        cca.setVisible(true);
    }//GEN-LAST:event_btnRetro1ActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        if(evt.getSource() == boton){
            valideRadios();
        }
    }//GEN-LAST:event_botonActionPerformed

    private void p1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_p1ItemStateChanged
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes_complementarias/P0001.jpg")));
    }//GEN-LAST:event_p1ItemStateChanged

    private void p2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_p2ItemStateChanged
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes_complementarias/P0002.jpg")));
    }//GEN-LAST:event_p2ItemStateChanged

    private void p3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_p3ItemStateChanged
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes_complementarias/P0003.jpg")));
    }//GEN-LAST:event_p3ItemStateChanged

    private void p4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_p4ItemStateChanged
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes_complementarias/P0004.jpg")));
    }//GEN-LAST:event_p4ItemStateChanged

    private void p5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_p5ItemStateChanged
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes_complementarias/P0005.jpg")));
    }//GEN-LAST:event_p5ItemStateChanged

    private void p6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_p6ItemStateChanged
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes_complementarias/P0006.jpg")));
    }//GEN-LAST:event_p6ItemStateChanged

    private void valideRadios(){
        if(p1.isSelected()){
            cad_P="P0001";
            Seleccionar(cad_P);
        }
        else if(p2.isSelected()){
            cad_P="P0002";
            Seleccionar(cad_P);
        }
        else if(p3.isSelected()){
            cad_P="P0003";
            Seleccionar(cad_P);
        }
        else if(p4.isSelected()){
            cad_P="P0004";
            Seleccionar(cad_P);
        }
        else if(p5.isSelected()){
            cad_P="P0005";
            Seleccionar(cad_P);
        }
        else if(p6.isSelected()){
            cad_P="P0006";
            Seleccionar(cad_P);
        }else{
            JOptionPane.showMessageDialog(this,"SELECCIONE UN ARTÍCULO");
        }
    }
    
    public static String cad_P=null;
    public void Seleccionar(String s){
        int r = JOptionPane.showConfirmDialog(null, "¿Está seguro de escoger el artículo "+s+"?");
        if(r==0){
            dispose();
            Calcular_Presupuesto cp=new Calcular_Presupuesto();
            cp.setLocationRelativeTo(null);
            cp.setVisible(true);
            
        }else{
            grupoDeradios.clearSelection();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteCatalogo_P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JButton btnRetro;
    private javax.swing.JButton btnRetro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p2;
    private javax.swing.JRadioButton p3;
    private javax.swing.JRadioButton p4;
    private javax.swing.JRadioButton p5;
    private javax.swing.JRadioButton p6;
    // End of variables declaration//GEN-END:variables
}
