/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author SAMIR
 */
public class Client_VisualizarBoleta extends javax.swing.JFrame {
DefaultTableModel boleta;
    /**
     * Creates new form Client_VisualizarBoleta
     */
    public Client_VisualizarBoleta() {
        initComponents();
        
        lblCliente.setText(Ventana_info_cliente.Nombres+" "+Ventana_info_cliente.Apellidos);
        lblDNI.setText(Ventana_info_cliente.Dni);
        lblCorreo.setText(Ventana_info_cliente.Correo);
        lblTelefono.setText(Ventana_info_cliente.Telefono);
        
        lblBoleta.setText(Login_clienteRegistrado.N_Boleta);
        lblContrasenia.setText(Login_clienteRegistrado.contrasenia);
        lblFecha.setText(Login_clienteRegistrado.fecha);
        lblVuelto.setText(""+Cliente_MontRestante.vuelto);
        
        tblBoleta.setBorder(new LineBorder(new Color(0, 0, 0)));
	tblBoleta.setFillsViewportHeight(true);
        boleta = new DefaultTableModel();
        boleta.addColumn("CANTIDAD");
        boleta.addColumn("DESCRIPCION");
        boleta.addColumn("P. UNIT.");
        boleta.addColumn("IMPORTE");
        tblBoleta.setModel(boleta);
        TableColumnModel column = tblBoleta.getColumnModel();
        
	column.getColumn(0).setPreferredWidth(40);
	column.getColumn(1).setPreferredWidth(480);
	column.getColumn(2).setPreferredWidth(30);
	column.getColumn(3).setPreferredWidth(30);
        listar();
    }
    
    /*arreglo_clases.Arreglo_Pedido ap = new Arreglo_Pedido();
    Pedido p = ap.Buscar_Dni(Login_clienteRegistrado.c.getDni());
    
    arreglo_clases.Arreglo_ArticuloPedido aap = new Arreglo_ArticuloPedido();
    Articulo_Pedido a = aap.Buscar(p.getN_boleta());*/
    
    void listar(){
        
		boleta.setRowCount(0);
		Object[] fila = {
		Login_clienteRegistrado.cantidad, 
                "Artíuclo de joyería modelo "+Login_clienteRegistrado.Id_articulo+", con detalles de "+Login_clienteRegistrado.medida+" en "+Login_clienteRegistrado.material+" con peso de "+Login_clienteRegistrado.peso,
		Ventana_info_cliente.montoTotal/Login_clienteRegistrado.cantidad,
                Ventana_info_cliente.montoTotal};
		boleta.addRow(fila);
    }
    
    public Icon setIcono(String url, JLabel label){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = label.getWidth();
        int alto = label.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblBoleta = new javax.swing.JTable();
        lblTelefono = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblVuelto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        lblBoleta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Teléfono:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 90, 20));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Recibe un vuelto de: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 210, -1));

        jLabel10.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cliente:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 90, 20));

        jLabel11.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Correo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 80, 20));

        jLabel14.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Fecha:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 90, 20));

        jLabel12.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("DNI:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 70, 20));

        lblCliente.setFont(new java.awt.Font("Candara Light", 1, 15)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 250, 20));

        lblDNI.setFont(new java.awt.Font("Candara Light", 1, 15)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 110, 20));

        lblCorreo.setFont(new java.awt.Font("Candara Light", 1, 15)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 230, 20));

        tblBoleta.setBackground(new java.awt.Color(255, 204, 204));
        tblBoleta.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        tblBoleta.setForeground(new java.awt.Color(0, 0, 0));
        tblBoleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, "", null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBoleta.setFillsViewportHeight(true);
        jScrollPane.setViewportView(tblBoleta);

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 760, 100));

        lblTelefono.setFont(new java.awt.Font("Candara Light", 1, 15)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 230, 20));

        lblFecha.setFont(new java.awt.Font("Candara Light", 1, 15)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 120, 20));

        lblVuelto.setFont(new java.awt.Font("Candara Light", 1, 15)); // NOI18N
        lblVuelto.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblVuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 90, 20));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/ok.png"))); // NOI18N
        jButton2.setText("   OK");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 102, 50));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Jr. Huallaga N° 533 Tda 712 - Cercado de Lima");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 390, -1));

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Correo. jairocornejovega@gmail.com");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 320, -1));

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cel. 912403610");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("18k y plata 950");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Confección de joyas de Oro de");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 250, -1));

        jLabel9.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Contraseña:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, -1));

        lblContrasenia.setFont(new java.awt.Font("Candara Light", 1, 15)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 20));

        lblBoleta.setFont(new java.awt.Font("Candara Light", 1, 15)); // NOI18N
        lblBoleta.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 110, 20));

        jLabel8.setFont(new java.awt.Font("Elephant", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Boleta:            N° ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 430, 210));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/chica_boleta.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 440, 400));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/fondo_flores(boleta).jpg"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Ventana_info_cliente vic = new Ventana_info_cliente();
        vic.setLocationRelativeTo(null);
        vic.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_VisualizarBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_VisualizarBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_VisualizarBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_VisualizarBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_VisualizarBoleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblBoleta;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblVuelto;
    private javax.swing.JTable tblBoleta;
    // End of variables declaration//GEN-END:variables
}
