/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author SAMIR
 */
public final class ClienteCatalogo_P extends javax.swing.JFrame {

    ButtonGroup grupoDeradios;
    /**
     * Creates new form ClienteCatalogo_P
     */
    public ClienteCatalogo_P() {
        initComponents();
        FuncionIcono("src/imagenes/P0001.jpg", lblP1);
        FuncionIcono("src/imagenes/P0002.jpg", lblP2);
        FuncionIcono("src/imagenes/P0003.jpg", lblP3);
        FuncionIcono("src/imagenes/P0004.jpg", lblP4);
        FuncionIcono("src/imagenes/P0005.jpg", lblP5);
        FuncionIcono("src/imagenes/P0006.jpg", lblP6);
        
        grupoDeradios = new ButtonGroup();
        
        grupoDeradios.add(p1);
        grupoDeradios.add(p2);
        grupoDeradios.add(p3);
        grupoDeradios.add(p4);
        grupoDeradios.add(p5);
        grupoDeradios.add(p6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        p1 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        p3 = new javax.swing.JRadioButton();
        p4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        p6 = new javax.swing.JRadioButton();
        lblP2 = new javax.swing.JLabel();
        p5 = new javax.swing.JRadioButton();
        lblP1 = new javax.swing.JLabel();
        lblP4 = new javax.swing.JLabel();
        lblP3 = new javax.swing.JLabel();
        lblP6 = new javax.swing.JLabel();
        lblP5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        boton = new javax.swing.JButton();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(446, 752));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CATALOGO DE ARTICULOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, 253, 25));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 112, 426, -1));

        jLabel2.setText("Seleccione el artículo de su agrado.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 52, 322, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 73, 426, -1));

        p1.setText("P0001");
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 263, -1, -1));

        p2.setText("P0002");
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 263, -1, -1));

        p3.setText("P0003");
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 445, -1, -1));

        p4.setText("P0004");
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 445, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setText("SECCION PULSERAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 81, -1, -1));

        p6.setText("P0006");
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 626, -1, -1));
        getContentPane().add(lblP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 132, 110, 113));

        p5.setText("P0005");
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 626, -1, -1));
        getContentPane().add(lblP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 132, 110, 113));
        getContentPane().add(lblP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 314, 110, 113));
        getContentPane().add(lblP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 314, 110, 113));
        getContentPane().add(lblP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 495, 110, 113));
        getContentPane().add(lblP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 495, 110, 113));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 438, 10));

        jButton1.setText("Regresar página");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, -1));

        jButton3.setText("Siguiente página");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 690, -1, -1));

        boton.setText("Seleccionar");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 690, -1, -1));

        lblFondo1.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_catalogo.jpg"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        ClienteCatalogo_A cca = new ClienteCatalogo_A();
        cca.setLocationRelativeTo(null);
        cca.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        ClienteCatalogo_C ccc = new ClienteCatalogo_C();
        ccc.setLocationRelativeTo(null);
        ccc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        if(evt.getSource() == boton){
            valideRadios();
        }
    }//GEN-LAST:event_botonActionPerformed

    private void valideRadios(){
        if(p1.isSelected()){
            cad_P="P0001";
            Seleccionar(cad_P);
        }
        else if(p2.isSelected()){
            cad_P="P0002";
            Seleccionar(cad_P);
        }
        else if(p3.isSelected()){
            cad_P="P0003";
            Seleccionar(cad_P);
        }
        else if(p4.isSelected()){
            cad_P="P0004";
            Seleccionar(cad_P);
        }
        else if(p5.isSelected()){
            cad_P="P0005";
            Seleccionar(cad_P);
        }
        else if(p6.isSelected()){
            cad_P="P0006";
            Seleccionar(cad_P);
        }else{
            JOptionPane.showMessageDialog(this,"SELECCIONE UN ARTÍCULO");
        }
    }
    
    public static String cad_P=null;
    public void Seleccionar(String s){
        int r = JOptionPane.showConfirmDialog(null, "¿Está seguro de escoger el artículo "+s+"?");
        if(r==0){
            dispose();
            Calcular_Presupuesto cp=new Calcular_Presupuesto();
            cp.setLocationRelativeTo(null);
            cp.setVisible(true);
            
        }else{
            grupoDeradios.clearSelection();
        }
    }
    
    public void FuncionIcono(String s, JLabel lbl){
        ImageIcon imagen = new ImageIcon(s);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(icono);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteCatalogo_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteCatalogo_P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP3;
    private javax.swing.JLabel lblP4;
    private javax.swing.JLabel lblP5;
    private javax.swing.JLabel lblP6;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p2;
    private javax.swing.JRadioButton p3;
    private javax.swing.JRadioButton p4;
    private javax.swing.JRadioButton p5;
    private javax.swing.JRadioButton p6;
    // End of variables declaration//GEN-END:variables
}
