
package gui;

import Conex.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Encarg_EditarEstado extends javax.swing.JFrame {

    public Encarg_EditarEstado() {
        initComponents();
        txtNroBoleta.setText(Encarg_PorEntreg.dato);
        txtMaterial.setText(Encarg_PorEntreg.material);
        txtPeso.setText(""+Encarg_PorEntreg.Peso_total);
        txtPago.setText(Encarg_PorEntreg.Estado_pago);
        if((Encarg_PorEntreg.Estado_entrega_trabajo).equals("POR ENTREGAR")){
            boxEntrega.setSelectedIndex(0);
        }else{
            boxEntrega.setSelectedIndex(1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNroBoleta = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JLabel();
        txtPeso = new javax.swing.JLabel();
        txtPago = new javax.swing.JLabel();
        boxEntrega = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("EDITAR ESTADO DE FABRICACIÓN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 460, -1));

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nº de Boleta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, -1));

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Material:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, -1));

        jLabel5.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Peso total a usar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, -1));

        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estado de Pago:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, -1));

        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, -1));

        txtNroBoleta.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtNroBoleta.setForeground(new java.awt.Color(0, 0, 0));
        txtNroBoleta.setText("jLabel8");
        getContentPane().add(txtNroBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 160, -1));

        txtMaterial.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtMaterial.setForeground(new java.awt.Color(0, 0, 0));
        txtMaterial.setText("jLabel9");
        getContentPane().add(txtMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, -1));

        txtPeso.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtPeso.setForeground(new java.awt.Color(0, 0, 0));
        txtPeso.setText("jLabel10");
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, -1));

        txtPago.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtPago.setForeground(new java.awt.Color(0, 0, 0));
        txtPago.setText("jLabel11");
        getContentPane().add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 160, -1));

        boxEntrega.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        boxEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POR ENTREGAR", "ENTREGADO" }));
        getContentPane().add(boxEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/guardar.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, 80));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/cancelar.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 80, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/herramientas.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 150, 150));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/fondo_piel.jpg"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        void Modificar_Trabajo_Entregado(String n_boleta){
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        
        try{
            PreparedStatement pst = cn.prepareStatement("UPDATE articulo_pedido SET ENTREGA_TRABAJO = 'ENTREGADO' WHERE N_BOLETA = '"+n_boleta+"'");
            pst.executeUpdate();
        }catch(SQLException e){
            mensaje("No se registró como trabajo entregado");
        }
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int r = JOptionPane.showConfirmDialog(null, "¿Está seguro de editar el estado?");
        if(r==0){
            String entrega=boxEntrega.getSelectedItem().toString();
            Modificar_Trabajo_Entregado(Encarg_PorEntreg.dato);
            
            mensaje("ESTADO DE ENTREGA MODIFICADO");
            this.dispose();
            Encarg_PorEntreg e=new Encarg_PorEntreg();
            e.setLocationRelativeTo(null);
            e.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        Encarg_PorEntreg e=new Encarg_PorEntreg();
        e.setLocationRelativeTo(null);
        e.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encarg_EditarEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encarg_EditarEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encarg_EditarEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encarg_EditarEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encarg_EditarEstado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEntrega;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtMaterial;
    private javax.swing.JLabel txtNroBoleta;
    private javax.swing.JLabel txtPago;
    private javax.swing.JLabel txtPeso;
    // End of variables declaration//GEN-END:variables
}
