/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Conex.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author diego
 */
public class Gestionar_Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Gestionar_Usuarios
     */
    private DefaultTableModel usu;
    
    public Gestionar_Usuarios() {
        initComponents();
        tblUsu.setBorder(new LineBorder(new Color(0, 0, 0)));
	tblUsu.setFillsViewportHeight(true);
	mostrarDatos("");
      
        lblAdd.setVisible(false);
        lblSet.setVisible(false);
        lblRemove.setVisible(false);
    }

    void mostrarDatos(String valor){
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        
        usu=new DefaultTableModel();
        usu.addColumn("ID");
	usu.addColumn("Nombres");
	usu.addColumn("Apellidos");
	usu.addColumn("DNI");
        usu.addColumn("Teléfono");
        usu.addColumn("Correo");
	usu.addColumn("Contraseña");
	usu.addColumn("Cargo");
	tblUsu.setModel(usu);
        TableColumnModel column = tblUsu.getColumnModel();
        
	column.getColumn(0).setPreferredWidth(0);
	column.getColumn(1).setPreferredWidth(40);
	column.getColumn(2).setPreferredWidth(40);
	column.getColumn(3).setPreferredWidth(20);
	column.getColumn(4).setPreferredWidth(20);
        column.getColumn(5).setPreferredWidth(90);
        column.getColumn(6).setPreferredWidth(20);
        column.getColumn(7).setPreferredWidth(20);
        
        String sql = "";
        if(valor.equals("")){
            sql = "SELECT * FROM usuarios_empresa";
        }else{
            sql = "SELECT * FROM usuarios_empresa WHERE (Cargo_usuario='"+valor+"')"; 
        }
        
        String []datos = new String[8];
        try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                
                usu.addRow(datos);
            }
            tblUsu.setModel(usu);
        }catch(SQLException ex){
            mensaje("No se pudo conectar con la Base de Datos");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnSet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsu = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        lblAdd = new javax.swing.JLabel();
        lblSet = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GESTIONAR USUARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 23, 340, -1));

        jLabel2.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("A continuación seleccione un usuario y escoja la acción a realizar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 420, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/mas.png"))); // NOI18N
        btnAdd.setContentAreaFilled(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(85, 25));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 80, 80));

        btnSet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/edit.png"))); // NOI18N
        btnSet.setContentAreaFilled(false);
        btnSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSetMouseExited(evt);
            }
        });
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });
        getContentPane().add(btnSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 80, 80));

        tblUsu.setBackground(new java.awt.Color(255, 153, 153));
        tblUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        tblUsu.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        tblUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblUsu.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblUsu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 740, 220));

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/cancelar.png"))); // NOI18N
        btnRemove.setContentAreaFilled(false);
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoveMouseExited(evt);
            }
        });
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 80, 80));

        lblAdd.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(0, 0, 0));
        lblAdd.setText("Nuevo usuario");
        getContentPane().add(lblAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 110, 20));

        lblSet.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblSet.setForeground(new java.awt.Color(0, 0, 0));
        lblSet.setText("Modificar usuario");
        getContentPane().add(lblSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 130, 20));

        lblRemove.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(0, 0, 0));
        lblRemove.setText("Eliminar usuario");
        getContentPane().add(lblRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 120, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/off.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 90, 40));

        lblFondo1.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/fondo_rosa.png.jpg"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static int fila=0;
    void mensaje(String s) {
		JOptionPane.showMessageDialog(this, s);
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        dispose();
        Agregar_Usuario au=new Agregar_Usuario();
        au.setLocationRelativeTo(null);
        au.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed
    public static String id = "";
    public static String nombres = "";
    public static String apellidos = "";
    public static String dni = "";
    public static String telefono = "";
    public static String correo = "";
    public static String cargo = "";
    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        try{
        fila=tblUsu.getSelectedRow();
        if(fila>-1){
            id=tblUsu.getValueAt(fila, 0).toString();
            nombres=tblUsu.getValueAt(fila, 1).toString();
            apellidos=tblUsu.getValueAt(fila, 2).toString();
            dni=tblUsu.getValueAt(fila, 3).toString();
            telefono=tblUsu.getValueAt(fila, 4).toString();
            correo=tblUsu.getValueAt(fila, 5).toString();
            cargo=tblUsu.getValueAt(fila, 6).toString();
            this.setVisible(false);
            Modificar_Usuario mu=new Modificar_Usuario();
            mu.setLocationRelativeTo(null);
            mu.setVisible(true);
        }else{
            mensaje("Seleccione una fila");
        }
        }catch(Exception e){
            mensaje("Seleccione una fila");
        }
    }//GEN-LAST:event_btnSetActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        try{
        int f=tblUsu.getSelectedRow();
	if(f>-1){
		int r = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el usuario?");
		if(r==0){
                    Conexion cc = new Conexion();
                    Connection cn = cc.conexion();
                    String cod = tblUsu.getValueAt(f,0).toString();
                    try{
                        PreparedStatement pst = cn.prepareStatement("DELETE FROM usuarios_empresa WHERE ID_Usuario = '"+cod+"'");
                        pst.executeUpdate();
                        mostrarDatos("");
			mensaje("USUARIO ELIMINADO");
                    }catch(SQLException e){
                        mensaje("No se eliminó el registro");
                    }
		}
		tblUsu.setSelectionMode(0);
	}else{
		mensaje("SELECCIONE UN USUARIO");
	}
        }catch(Exception e){
		mensaje("SELECCIONE UN USUARIO");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    Ventana_Administrador va=new Ventana_Administrador();
    va.setLocationRelativeTo(null);
    va.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        lblAdd.setVisible(true);
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        lblAdd.setVisible(false);
    }//GEN-LAST:event_btnAddMouseExited

    private void btnSetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetMouseEntered
        lblSet.setVisible(true);
    }//GEN-LAST:event_btnSetMouseEntered

    private void btnSetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetMouseExited
        lblSet.setVisible(false);
    }//GEN-LAST:event_btnSetMouseExited

    private void btnRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseEntered
       lblRemove.setVisible(true);
    }//GEN-LAST:event_btnRemoveMouseEntered

    private void btnRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseExited
        lblRemove.setVisible(false);
    }//GEN-LAST:event_btnRemoveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestionar_Usuarios().setVisible(true);
            }
        });
    }
		
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSet;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblSet;
    private javax.swing.JTable tblUsu;
    // End of variables declaration//GEN-END:variables
}
