/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import Conex.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author SAMIR
 */
public class Login_clienteRegistrado extends javax.swing.JFrame {
    public static boolean Mostrar = false;
    /** Creates new form Login_clienteRegistrado */
    public Login_clienteRegistrado() {
        initComponents();
        txtPass_Cliente.setVisible(true);
        txtPass_Cliente_Visible.setVisible(false);
        
        //boton ver
        btnVer.setIcon(setIcono("/imagenes_interfaces/ver.png", btnVer));
        btnVer.setPressedIcon(setIconoPresionado("/imagenes_interfaces/ver.png", btnVer, 3, 3));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPass_Cliente = new javax.swing.JPasswordField();
        txtBoleta_Cliente = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        txtPass_Cliente_Visible = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        lblIcono_Cliente = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPass_Cliente.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        getContentPane().add(txtPass_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 143, -1));

        txtBoleta_Cliente.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        getContentPane().add(txtBoleta_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 143, -1));

        btnAtras.setBackground(new java.awt.Color(255, 255, 153));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/atras.png"))); // NOI18N
        btnAtras.setContentAreaFilled(false);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        txtPass_Cliente_Visible.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        getContentPane().add(txtPass_Cliente_Visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 143, -1));

        jLabel1.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Atrás");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 20));

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("N° Boleta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 208, 90, 24));

        jLabel5.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, -1));

        btnVer.setContentAreaFilled(false);
        btnVer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 242, -1, 30));

        btnIngresar.setBackground(new java.awt.Color(255, 255, 153));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/siguiente.png"))); // NOI18N
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIngresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 70, 70));

        lblIcono_Cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/cliente.png"))); // NOI18N
        lblIcono_Cliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblIcono_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, 160));

        lblFondo.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/fondo_general.jpg"))); // NOI18N
        lblFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int a=3;
    
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        dispose();
        Ventana_clientes vc = new Ventana_clientes();
        vc.setLocationRelativeTo(null);
        vc.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        if(Mostrar){
            txtPass_Cliente.setText(txtPass_Cliente_Visible.getText());
            txtPass_Cliente.setVisible(true);
            txtPass_Cliente_Visible.setVisible(false);
            Mostrar = false;
        }else{
            txtPass_Cliente_Visible.setText(txtPass_Cliente.getText());
            txtPass_Cliente.setVisible(false);
            txtPass_Cliente_Visible.setVisible(true);
            Mostrar = true;
        }
    }//GEN-LAST:event_btnVerActionPerformed
    
    //VARIABLES STATIC 
    public static String model_articulo= "";
    public static String contrasenia = "";
    public static String fecha = "";
    public static String dni_cliente = "";
    public static String N_Boleta = "";
    public static String Id_articulo = "";
    public static String medida = "";
    public static String material = "";
    public static double peso = 0.0;
    public static double monto_amortiguado = 0.0;
    public static int cantidad = 0;
    public static String Estado_Fabricacion = "";
    public static String Estado_Entrega_Trabajo = "";
    public static String Pago_Estado = "";
    public static String Entrega_Material = "";
    
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        LoginCliente_Registrado();
    }//GEN-LAST:event_btnIngresarActionPerformed
    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    
    void LoginCliente_Registrado(){
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        
        try{
            String nroboleta=txtBoleta_Cliente.getText().trim();
            
            if(nroboleta.length()>0){
                char[] clave= txtPass_Cliente.getPassword();
		String contraseña=new String(clave).trim();
               
                
                
                if(contraseña.length()>0){
                    String sentencia_buscar = ("SELECT N_boleta, DNI, Contrasenia_boleta, Fecha_pedido FROM pedido WHERE N_boleta = '"+nroboleta+"' AND Contrasenia_boleta = '"+contraseña+"'");
                    
                    PreparedStatement pst = cn.prepareStatement(sentencia_buscar);

                    ResultSet resultado = pst.executeQuery();
                    
                    if(resultado.next()){
                        fecha = resultado.getString("Fecha_pedido");
                        contrasenia = resultado.getString("Contrasenia_boleta");
                        dni_cliente = resultado.getString("DNI");
                        mensaje("¡¡¡BIENVENIDO!!!");
                        dispose();
                        
                        String sentencia_buscar_ArticuloPedido = ("SELECT N_BOLETA, SOLICITUD_A, MEDIDA, MATERIAL, PESO, MONTO_AMORTIGUADO, CANTIDAD, FABRICACION, ENTREGA_TRABAJO, PAGO_ESTADO, ENTREGA_MATERIAL FROM articulo_pedido WHERE N_boleta = '"+nroboleta+"'");
                        PreparedStatement pstArticulo_pedido = cn.prepareStatement(sentencia_buscar_ArticuloPedido);
                        
                        ResultSet resultado_articulopedido = pstArticulo_pedido.executeQuery();
                        
                        if(resultado_articulopedido.next()){
                            //Guardamos el número de solicitud
                            String n_solicitud = resultado_articulopedido.getString("SOLICITUD_A");
                            
                            String sentencia_buscar_Articulo = ("SELECT SOLICITUD, ID, DIRECCION_CASA, ESTADO from DIRECCION WHERE SOLICITUD = '"+n_solicitud+"'");
                            PreparedStatement pstArticulo = cn.prepareStatement(sentencia_buscar_Articulo);

                            ResultSet resultado_articulo = pstArticulo.executeQuery();

                            if(resultado_articulo.next()){
                                Id_articulo =resultado_articulo.getString("ID");
                            }
                            N_Boleta = resultado_articulopedido.getString("N_BOLETA");
                            medida = resultado_articulopedido.getString("MEDIDA");
                            material = resultado_articulopedido.getString("MATERIAL");
                            peso = resultado_articulopedido.getDouble("PESO");
                            monto_amortiguado = resultado_articulopedido.getDouble("MONTO_AMORTIGUADO");
                            cantidad = resultado_articulopedido.getInt("CANTIDAD");
                            Estado_Fabricacion = resultado_articulopedido.getString("FABRICACION");
                            Estado_Entrega_Trabajo = resultado_articulopedido.getString("ENTREGA_TRABAJO");
                            Pago_Estado = resultado_articulopedido.getString("PAGO_ESTADO");
                            Entrega_Material = resultado_articulopedido.getString("ENTREGA_MATERIAL");
                            
                            if(Estado_Fabricacion.equals("TERMINADO")){
                                if(Estado_Entrega_Trabajo.equals("ENTREGADO")){
                                    Ventana_info_cliente vc=new Ventana_info_cliente();
                                        vc.setLocationRelativeTo(null);
                                        vc.setVisible(true);
                                }else{
                                    model_articulo = Id_articulo;
                                    Confirmacion c = new Confirmacion();
                                    c.setLocationRelativeTo(null);
                                    c.setVisible(true);
                                }
                            }else{
                                Ventana_info_cliente vc=new Ventana_info_cliente();
                                    vc.setLocationRelativeTo(null);
                                    vc.setVisible(true);
                            }
                        }
                        
                    }else{
                        a--;
				if(a==0){
                                    mensaje("Límite de intentos alcanzados\n\tSe cerrará el sistema");
					System.exit(0);
				}else{
					mensaje("Usuario y/o contraseña incorrecta\n\tIntentos restantes: "+a);
					txtBoleta_Cliente.setText("");
					txtPass_Cliente.setText("");
                                        txtPass_Cliente_Visible.setText("");
                                        txtPass_Cliente_Visible.setVisible(false);
                                        txtPass_Cliente.setVisible(true);
					txtBoleta_Cliente.grabFocus();
				}
                    }
                    
                    
                }else{
                mensaje("INGRESE CONTRASEÑA");
                txtPass_Cliente.setText("");
                txtPass_Cliente.grabFocus();
                }
            }else{
                mensaje("RELLENE EL CAMPO N° BOLETA");
                txtBoleta_Cliente.setText("");
                txtBoleta_Cliente.grabFocus();
            }
        
        }catch(SQLException e){
            mensaje("Se produjo un error: "+e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_clienteRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_clienteRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_clienteRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_clienteRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_clienteRegistrado().setVisible(true);
            }
        });
    }
    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = boton.getWidth() - 6;
        int alto = boton.getHeight() - 6;
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth()-ancho;
        int height = boton.getHeight()-altura;
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono_Cliente;
    private javax.swing.JTextField txtBoleta_Cliente;
    private javax.swing.JPasswordField txtPass_Cliente;
    private javax.swing.JTextField txtPass_Cliente_Visible;
    // End of variables declaration//GEN-END:variables

}
