/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Conex.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Modificar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Modificar_Usuario
     */
    public Modificar_Usuario() {
        initComponents();
        
        txtNombres.setText(Gestionar_Usuarios.nombres);
        txtApellidos.setText(Gestionar_Usuarios.apellidos);
        txtDni.setText(Gestionar_Usuarios.dni);
        txtCorreo.setText(Gestionar_Usuarios.correo);
        txtTelefono.setText(Gestionar_Usuarios.telefono);
        switch (Gestionar_Usuarios.cargo) {
            case "Administrador":
                comBox.setSelectedIndex(0);
                break;
            case "Encargado":
                comBox.setSelectedIndex(1);
                break;
            default:
                comBox.setSelectedIndex(2);
                break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        comBox = new javax.swing.JComboBox<>();
        txtContra = new javax.swing.JPasswordField();
        txtConfContra = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("MODIFICAR USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 61, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Apellidos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 98, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("DNI:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 61, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Correo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 98, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Cargo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 134, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Confirmar Contraseña:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Celular:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 134, -1, -1));

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 60, 90, -1));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 97, 90, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 133, 90, -1));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 60, 90, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 97, 150, -1));

        comBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Encargado", "Trabajador" }));
        getContentPane().add(comBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 130, 108, -1));
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 197, 90, -1));
        getContentPane().add(txtConfContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 229, 90, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setText("Confirmar modificación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 186, 178, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 172, 255, 10));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 244, -1, -1));

        lblFondo1.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/color_ventanas.jpg"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Modificar_Usuario();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    void Modificar_Usuario(){
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        try{
            String Nombre_usuario = txtNombres.getText();
            String Apellido_usuario = "";
            String DNI_usuario = "";
            String Telefono_usuario = "";
            String Correo_usuario = "";
            String Cargo_usuario = "";
            if(Nombre_usuario.length()>0){
                Apellido_usuario = txtApellidos.getText();
                if(Apellido_usuario.length()>0){
                    DNI_usuario = txtDni.getText();
                    if(DNI_usuario.length()>0){
                        Telefono_usuario = txtTelefono.getText();
                        if(Telefono_usuario.length()>0){
                            Correo_usuario = txtCorreo.getText();
                            if(Correo_usuario.length()>0){
                                    char[] cont=txtContra.getPassword();
                                    String contra=new String(cont).trim();
                                    
                                    if(contra.length()>0){
                                        char[] confcont=txtConfContra.getPassword();
                                        String confcontra=new String(confcont).trim();
                                        
                                        if(confcontra.length()>0){
                                            if(contra.equals(confcontra)){
                                                Cargo_usuario = comBox.getSelectedItem().toString();
                                                PreparedStatement pst = cn.prepareStatement("UPDATE usuarios_empresa SET Nombres_usuario ='"+Nombre_usuario+"', Apellidos_usuario = '"+Apellido_usuario+"', DNI_usuario = '"+DNI_usuario+"', Telefono_usuario = '"+Telefono_usuario+"', Correo_usuario = '"+Correo_usuario+"', Contrasenia_usuario = '"+contra+"', Cargo_usuario = '"+Cargo_usuario+"' WHERE ID_Usuario = '"+Gestionar_Usuarios.id+"' ");
                                                pst.executeUpdate();
                                                mensaje("USUARIO MODIFICADO");
                                                    dispose();
                                                    Gestionar_Usuarios gu=new Gestionar_Usuarios();
                                                    gu.setLocationRelativeTo(null);
                                                    gu.setVisible(true);
                                            }else{
                                                mensaje("Las contraseñas no coinciden");
                                                txtConfContra.setText("");
                                                txtContra.setText("");
                                                txtContra.grabFocus();
                                            }
                                        }else{
                                            mensaje("Rellene el campo Confirmación Contraseña correctamente");
                                            txtConfContra.setText("");
                                            txtConfContra.grabFocus();
                                        }
                                    }else{
                                        mensaje("Rellene el campo Contraseña correctamente");
                                        txtContra.setText("");
                                        txtContra.grabFocus();
                                    }
                            }else{
                                mensaje("Rellene el campo Correo correctamente");
                                txtCorreo.setText("");
                                txtCorreo.grabFocus();
                            }
                        }else{
                            mensaje("Rellene el campo Teléfono correctamente");
                            txtTelefono.setText("");
                            txtTelefono.grabFocus();
                        }
                    }else{
                mensaje("Rellene el campo DNI correctamente");
                txtDni.setText("");
                txtDni.grabFocus();
                    }
                }else{
                mensaje("Rellene el campo apellidos correctamente");
                txtApellidos.setText("");
                txtApellidos.grabFocus();
                }
            }else{
                mensaje("Rellene el campo nombre correctamente");
                txtNombres.setText("");
                txtNombres.grabFocus();
            }
            
            
        }catch(SQLException e){
            
            
        }
    }
    
    void mensaje(String s) {
		JOptionPane.showMessageDialog(this, s);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Gestionar_Usuarios gu=new Gestionar_Usuarios();
        gu.setLocationRelativeTo(null);
        gu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtConfContra;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
