/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Conex.Conexion;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Registro_Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Pedido
     */
    public Registro_Pedido() {
        initComponents();
        lblId.setText(Registro_Solicitudes.ID_articulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMedida = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        txtMontoT = new javax.swing.JTextField();
        txtMontoA = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        comBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtCant = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        cmbAnio = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox<>();
        lblFondo4 = new javax.swing.JLabel();
        lblFondo5 = new javax.swing.JLabel();
        lblFondo6 = new javax.swing.JLabel();
        lblFondo7 = new javax.swing.JLabel();
        lblFondo8 = new javax.swing.JLabel();
        lblFondo9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel1.setText("REGISTRO DE PEDIDOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 82, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("DNI: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 82, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Apellidos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 128, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Correo: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 165, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 80, 94, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 117, 100, -1));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 80, 102, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 163, 167, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Talla,Medida:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 307, 81, -1));
        getContentPane().add(txtMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 305, 151, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 126, 102, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Peso (gr.):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 307, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel9.setText("DATOS DEL CLIENTE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 49, -1, -1));
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 305, 98, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Material:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 353, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Monto Total:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 402, -1, -1));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel10.setText("DATOS DEL PEDIDO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 227, 218, 30));

        label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label.setText("Fecha de pedido:");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 110, -1));

        txtMontoT.setEditable(false);
        getContentPane().add(txtMontoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 400, 85, -1));

        txtMontoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoAActionPerformed(evt);
            }
        });
        getContentPane().add(txtMontoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 450, 97, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Registrar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 141, 43));

        comBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ORO", "PLATA", "BRONCE" }));
        getContentPane().add(comBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 348, 100, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Cantidad:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 353, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));
        getContentPane().add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 351, 98, -1));

        jButton3.setText("Calcular presupuesto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 397, 152, -1));

        lblId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 268, 85, 19));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("ID del artículo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 272, 91, -1));

        label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label1.setText("Monto amortiguado:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 452, -1, -1));

        cmbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "(----)" }));
        getContentPane().add(cmbAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 495, 90, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 211, 457, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("/");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 495, 10, 20));

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMesItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 495, 100, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("/");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 495, 10, 20));

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 495, 70, -1));

        lblFondo4.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 300));

        lblFondo5.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 300));

        lblFondo6.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 300));

        lblFondo7.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 230, 300));

        lblFondo8.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 50, 300));

        lblFondo9.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 50, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    public String leerNombre(){
        return txtNombre.getText().trim();
    }
    public String leerApellido(){
        return txtApellido.getText().trim();
    }
    public String leerDNI(){
        return txtDni.getText().trim();
    }
    public String leerTelefono(){
        return txtTelefono.getText().trim();
    }
    public String leerCorreo(){
        return txtCorreo.getText().trim();
    }
    public String leerMedida_Talla(){
        return txtMedida.getText().trim();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegistrarPedido();
    }//GEN-LAST:event_jButton1ActionPerformed

    public double Monto_Total(){
        double presupuesto = 0;
        String s = comBox.getSelectedItem().toString();
        int cantidad = Integer.parseInt(txtCant.getText().trim());
        double peso = Double.parseDouble(txtPeso.getText().trim());
        switch (s) {
            case "ORO":
                presupuesto = peso*(3.68)*45*cantidad;
                break;
            case "PLATA":
                presupuesto = peso*7*cantidad;
                break;
            default:
                presupuesto = peso*4.5*cantidad;
                break;
        }
        return presupuesto;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Registro_Solicitudes rs=new Registro_Solicitudes();
        rs.setLocationRelativeTo(null);
        rs.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s = " ";
        int cantidad = 0;
        double peso = 0.0;
        double presupuesto = 0.0;
        s=comBox.getSelectedItem().toString();
        try{
        cantidad = Integer.parseInt(txtCant.getText().trim());
        try{
        peso=Double.parseDouble(txtPeso.getText().trim());
        switch (s) {
            case "ORO":
                presupuesto = peso*(3.68)*45*cantidad;
                break;
            case "PLATA":
                presupuesto = peso*7*cantidad;
                break;
            default:
                presupuesto = peso*4.5*cantidad;
                break;
        }
        txtMontoT.setText(String.format("%.2f",presupuesto));
        }catch(Exception e){
           mensaje("No se puede calcular el presupuesto, sin ingresar un peso específico");
            txtPeso.setText(""); 
        }
        }catch(Exception e){
            mensaje("No se puede calcular el presupuesto, sin ingresar una cantidad en específico");
            txtCant.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtMontoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoAActionPerformed

    private void cmbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMesItemStateChanged
        int pos = cmbMes.getSelectedIndex();
        switch (pos){
            case 0:{
                break;
            }
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
                break;
            case 2:{
                cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29" }));
                break;
            }
            default:{
                cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
                break;
            }
        }
        
    }//GEN-LAST:event_cmbMesItemStateChanged
    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    
    void RegistrarPedido(){
        String nombre=leerNombre();
        if(nombre.length()>0){
            String apellido=leerApellido();
            if(apellido.length()>0){
                String dni=leerDNI();
                    if(dni.length()>0 && dni.length()<9){
                        String telefono=leerTelefono();
                           if(telefono.length()>0 && telefono.length()<10){
                                String correo=leerCorreo();
                                if(correo.length()>0){
                                    String medida_talla=leerMedida_Talla();
                                        if(medida_talla.length()>0){
                                            String material=comBox.getSelectedItem().toString();
                                            if(material.length()>0){
                                               try{
                                                   double peso=Double.parseDouble(txtPeso.getText().trim());
                                               try{
                                                       int cantidad = Integer.parseInt(txtCant.getText().trim());
                                                        try{
                                                              double montoamortiguado=Double.parseDouble(txtMontoA.getText());
                                                              if(montoamortiguado >= Monto_Total()){
                                                                  mensaje("No se puede registrar el monto de "+montoamortiguado+" ya que excede o es igual al Monto Total");
                                                                  txtMontoA.setText("");
                                                              }else{
                                                                  String dia_pedido = cmbDia.getSelectedItem().toString();
                                                                  if(dia_pedido.equals("Día")){
                                                                      mensaje("Seleccione un día en específico");
                                                                  }else{
                                                                      String mes_pedido = cmbMes.getSelectedItem().toString();
                                                                      if(mes_pedido.equals("Mes")){
                                                                          mensaje("Seleccione un mes en específico");
                                                                      }else{
                                                                          String anio_pedido = cmbAnio.getSelectedItem().toString();
                                                                          if(anio_pedido.equals("Año") || anio_pedido.equals("(----)")){
                                                                              mensaje("Seleccione un año en específico");
                                                                          }else{
                                                                              switch(mes_pedido){
                                                                                  case "Enero":
                                                                                      mes_pedido = "01";
                                                                                      break;
                                                                                  case "Febrero":
                                                                                      mes_pedido = "02";
                                                                                      break;
                                                                                  case "Marzo":
                                                                                      mes_pedido = "03";
                                                                                      break;
                                                                                  case "Abril":
                                                                                      mes_pedido = "04";
                                                                                      break;
                                                                                  case "Mayo":
                                                                                      mes_pedido = "05";
                                                                                      break;
                                                                                  case "Junio":
                                                                                      mes_pedido = "06";
                                                                                      break;
                                                                                  case "Julio":
                                                                                      mes_pedido = "07";
                                                                                      break;
                                                                                  case "Agosto":
                                                                                      mes_pedido = "08";
                                                                                      break;
                                                                                  case "Setiembre":
                                                                                      mes_pedido = "09";
                                                                                      break;
                                                                                  case "Octubre":
                                                                                      mes_pedido = "10";
                                                                                      break;
                                                                                  case "Noviembre":
                                                                                      mes_pedido = "11";
                                                                                      break;
                                                                                  case "Diciembre":
                                                                                      mes_pedido = "12";
                                                                                      break;
                                                                              }
                                                                                Conexion cc = new Conexion();
                                                                                Connection cn = cc.conexion();
        
                                                                                
                                                                                try{
                                                                                    //REGISTRO DE CLIENTE
                                                                                    PreparedStatement pst_cliente = cn.prepareStatement("INSERT INTO clientes(Nombres_cliente, Apellidos_cliente, DNI_cliente, Telefono_cliente, Correo_cliente) VALUES(?,?,?,?,?)");
                                                                                    pst_cliente.setString(1, nombre);
                                                                                    pst_cliente.setString(2, apellido);
                                                                                    pst_cliente.setString(3, dni);
                                                                                    pst_cliente.setString(4, telefono);
                                                                                    pst_cliente.setString(5, correo);
                                                                                    
                                                                                    //EJECUTAR EL INSERTAR CLIENTE
                                                                                    pst_cliente.executeUpdate();
                                                                                    
                                                                                    try{
                                                                                        
                                                                                        //MODIFICANDO DIRECCION COMO 'Registrado'
                                                                                        String articulo=Registro_Solicitudes.ID_articulo;
                                                                                        PreparedStatement pst_Direccion_modificar = cn.prepareStatement("UPDATE direccion SET Estado ='Registrado' WHERE ID = '"+articulo+"' ");
                                                                                        
                                                                                        //EJECUTAR EL MODIFICAR DIRECCION
                                                                                        pst_Direccion_modificar.executeUpdate();
                                                                                        
                                                                                        //Contando pedidos
                                                                                        try{
                                                                                            
                                                                                            int cant=1;
                                                                                            String sql_pedido = "SELECT * FROM pedido";
        
                                                                                            try{
                                                                                                Statement st = cn.createStatement();
                                                                                                ResultSet rs = st.executeQuery(sql_pedido);
                                                                                                while(rs.next()){
                                                                                                    cant++;
                                                                                                }
                                                                                            }catch(SQLException ex){
                                                                                                mensaje("No se pudo conectar con la Base de Datos");
                                                                                            }
                                                                                            
                                                                                            
                                                                                            String N_boleta = "0000"+cant;
                                                                                            int cont=(int)(Math.random()*9999 + 1);
                                                                                            String contrasenia = ""+cont;
                                                                                            String fecha_pedido = dia_pedido + "-" + mes_pedido + "-" + anio_pedido;

                                                                                        //CREANDO UN NUEVO PEDIDO
                                                                                        PreparedStatement pst_pedido = cn.prepareStatement("INSERT INTO pedido(N_boleta, DNI, Contrasenia_boleta, Fecha_pedido) VALUES(?,?,?,?)");
                                                                                           pst_pedido.setString(1, N_boleta);
                                                                                           pst_pedido.setString(2, dni);
                                                                                           pst_pedido.setString(3, contrasenia);
                                                                                           pst_pedido.setString(4,fecha_pedido);
                                                                                           
                                                                                           //EJECUTAR EL INSERTAR NUEVO PEDIDO
                                                                                           pst_pedido.executeUpdate();
                                                                                           
                                                                                           try{
                                                                                               //CREANDO NUEVO ARTICULO_PEDIDO
                                                                                            PreparedStatement pst_articulopedido = cn.prepareStatement("INSERT INTO articulo_pedido(N_boleta, ID_articulo, Medida, Material, Peso, Monto_Amortiguado, Cantidad, Fabricacion, Entrega_trabajo, Pago_estado, Entrega_material) VALUES(?,?,?,?,?,?,?,?,?,?,?)");
                                                                                            pst_articulopedido.setString(1,N_boleta);
                                                                                            pst_articulopedido.setString(2,articulo);
                                                                                            pst_articulopedido.setString(3,medida_talla);
                                                                                            pst_articulopedido.setString(4,material);
                                                                                            pst_articulopedido.setDouble(5,peso);
                                                                                            pst_articulopedido.setDouble(6,montoamortiguado);
                                                                                            pst_articulopedido.setInt(7,cantidad);
                                                                                            pst_articulopedido.setString(8,"SIN FABRICAR");
                                                                                            pst_articulopedido.setString(9,"POR ENTREGAR");
                                                                                            pst_articulopedido.setString(10,"SIN CANCELAR");
                                                                                            pst_articulopedido.setString(11,"SIN ENTREGAR");
                                                                                            
                                                                                            //EJECUTAR EL INSERTAR NUEVO ARTICULO_PEDIDO
                                                                                            pst_articulopedido.executeUpdate();
                                                                                            
                                                                                            
                                                                                            mensaje("PEDIDO REGISTRADO");
                                                                                            dispose();
                                                                                            Registro_Solicitudes rs=new Registro_Solicitudes();
                                                                                            rs.setLocationRelativeTo(null);
                                                                                            rs.setVisible(true);
                                                                                           }catch(SQLException e){
                                                                                               mensaje("No se registro el pedido completo del artículo "+e.getMessage());
                                                                                           }
                                                                                        }catch(SQLException e){
                                                                                            mensaje("No se registro el pedido "+e.getMessage());
                                                                                        }
                                                                                    }catch(SQLException e){
                                                                                        mensaje("No se modificó la dirección");
                                                                                    }
                                                                                }catch(SQLException e){
                                                                                    mensaje("No se registro un nuevo cliente");
                                                                                }                                                                              
                                                                          }
                                                                      }
                                                                  }
                                                              }
                                                              
                                   }catch(Exception e){
                                       mensaje("RELLENE CORRECTAMENTE EL CAMPO MONTO AMORTIGUADO");
                                       label.setText("");
                                   }
                                     }catch(Exception e){
                                            mensaje("RELLENE CORRECTAMENTE EL CAMPO CANTIDAD");
                                            txtCant.setText("");
                                     }     
                                }catch(Exception e){
                                    mensaje("RELLENE CORRECTAMENTE EL CAMPO PESO");
                                    txtPeso.setText("");
                                }
                             }else{
                                 mensaje("RELLENE CORRECTAMENTE EL CAMPO MATERIAL");
                             }
                         }else{
                             mensaje("RELLENE CORRECTAMENTE EL CAMPO MEDIDA/TALLA");
                             txtMedida.setText("");
                         }
                     }else{
                         mensaje("RELLENE CORRECTAMENTE EL CAMPO CORREO");
                         txtCorreo.setText("");
                     }
                }else{
                    mensaje("RELLENE CORRECTAMENTE EL CAMPO TELEFONO");
                    txtDni.setText("");
                }
                }else{
                    mensaje("RELLENE CORRECTAMENTE EL CAMPO DNI");
                    txtDni.setText("");
                }
            }else{
                mensaje("RELLENE CORRECTAMENTE EL CAMPO APELLIDOS");
                txtApellido.setText("");
            }
        }else{
            mensaje("RELLENE CORRECTAMENTE EL CAMPO NOMBRE");
            txtNombre.setText("");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAnio;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<String> comBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lblFondo4;
    private javax.swing.JLabel lblFondo5;
    private javax.swing.JLabel lblFondo6;
    private javax.swing.JLabel lblFondo7;
    private javax.swing.JLabel lblFondo8;
    private javax.swing.JLabel lblFondo9;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtMedida;
    private javax.swing.JTextField txtMontoA;
    private javax.swing.JTextField txtMontoT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
