/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Conex.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Registrar_Direccion extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_Direccion
     */
    public Registrar_Direccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnRetro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("<html>Se registra la direccion del cliente para que uno de nuestros empleados realice una visita para tomar los datos necesario para la elaboración del artículo</html>");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 52, 337, -1));

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dirección: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRAR DIRECCIÓN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, 310, -1));
        getContentPane().add(txtD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 260, 90));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/casa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 70, 60));

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("<html><center>Registrar <p>Detalles");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 110, -1));

        btnRetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/retroceder.png"))); // NOI18N
        btnRetro.setContentAreaFilled(false);
        btnRetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 60, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/Fondo_Ventana_Admin.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String leerID(){
            if(ClienteCatalogo_A.cad_A != null){
                return ClienteCatalogo_A.cad_A;
            }
            if(ClienteCatalogo_C.cad_C != null){
                return ClienteCatalogo_C.cad_C;
            }
            if(ClienteCatalogo_P.cad_P != null){
                return ClienteCatalogo_P.cad_P;
            }
            if(ClienteCatalogo_S.cad_S != null){
                return ClienteCatalogo_S.cad_S;
            }
            return null;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String texto=txtD.getText();
        if(texto.length()>0){   
            int r = JOptionPane.showConfirmDialog(null, "¿Confirma su dirección como '"+texto+"' ?");
        if(r==0){
            RegistrarDireccion(texto);
        }
        }else{
            mensaje("DIRECCIÓN OBLIGATORIA PARA EL REGISTRO DE SU SOLICITUD");
            txtD.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetroActionPerformed
         int r = JOptionPane.showConfirmDialog(null, "¿Desea cancelar solicitud?");
         if(r==0){
            dispose();
            ClienteCatalogo_S vc = new ClienteCatalogo_S();
            vc.setLocationRelativeTo(null);
            vc.setVisible(true);
         }        
    }//GEN-LAST:event_btnRetroActionPerformed
    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    
    void RegistrarDireccion(String texto){
        Conexion cc = new Conexion();
            Connection cn = cc.conexion();
                try {
                    PreparedStatement pst = cn.prepareStatement("INSERT INTO direccion(SOLICITUD,ID,DIRECCION_CASA,ESTADO) VALUES(?,?,?,?)");
                    
                    
                    int cant=1;
                    String sql_pedido = "SELECT * FROM direccion";

                    try{
                        Statement st = cn.createStatement();
                        ResultSet rs = st.executeQuery(sql_pedido);
                        while(rs.next()){
                            cant++;
                        }
                    }catch(SQLException ex){
                        mensaje("No se pudo conectar con la Base de Datos");
                    }
                    
                    
                    String N_solicitud = "S"+cant;
                    
                    pst.setString(1, N_solicitud);
                    pst.setString(2,leerID());
                    pst.setString(3,texto);
                    pst.setString(4,"No registrado");
                    
                    int a = pst.executeUpdate();
                    if(a>0){
                        mensaje("DIRECCIÓN REGISTRADA");
                    }else{
                        mensaje("ERROR AL REGISTRAR");
                    }
                    dispose();
                    Ventana_principal vp=new Ventana_principal(this, true);
                    vp.setLocationRelativeTo(null);
                    vp.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Registrar_Direccion.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_Direccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_Direccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtD;
    // End of variables declaration//GEN-END:variables

}
