
package gui;

import Conex.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;


public class Trabaj_RegistroTrabajos extends javax.swing.JFrame {

    private DefaultTableModel trab;
    public Trabaj_RegistroTrabajos() {
        initComponents();
        tblTrab.setBorder(new LineBorder(new Color(0, 0, 0)));
	tblTrab.setFillsViewportHeight(true);
        listar_Registro_Trabajos();
    }
    
    public static String dato="";
    void listar_Registro_Trabajos(){
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        
        trab=new DefaultTableModel();
        trab.addColumn("Nº Boleta");
        trab.addColumn("Material");
        trab.addColumn("Peso Total");
        trab.addColumn("Entrega Material");
        trab.addColumn("Estado de Fabricación");
        tblTrab.setModel(trab);
        
        String sql = "SELECT * FROM articulo_pedido";
        
        String []datos = new String[5];
        try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(4);
                datos[2] = ""+(rs.getDouble(5)*rs.getInt(7));
                datos[3] = rs.getString(11);
                datos[4] = rs.getString(8);
                trab.addRow(datos);
            }
            tblTrab.setModel(trab);
        }catch(SQLException ex){
            mensaje("No se pudo conectar con la Base de Datos");
        }
    }
    
    //VARIABLES STATIC
    
    public static String N_boleta = "";
    public static String Material = "";
    public static double p_total = 0.0;
    public static String Estado_material = "";
    public static String Estado_fabricacion = "";
    
    
    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSolicitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrab = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("<html>En esta sección usted tendrá acceso a u registro de trabajos donde podrá solicitar el material necesario para la fabricación. A su vez, también podrá editar el registro pero unicamente el \"ESTADO DE FABRICACIÓN\", para saber si el trabajo está: \"SIN FABRICAR\",\"FABRICANDO\" o \"TERMINADO\".</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 575, 50));

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTRO DE TRABAJOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, -1));

        btnSolicitar.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        btnSolicitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/solicitud_material.png"))); // NOI18N
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 110, 100));

        tblTrab.setBackground(new java.awt.Color(255, 153, 153));
        tblTrab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        tblTrab.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        tblTrab.setForeground(new java.awt.Color(255, 255, 255));
        tblTrab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTrab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblTrab.setFocusable(false);
        tblTrab.setGridColor(new java.awt.Color(204, 204, 204));
        tblTrab.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblTrab.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblTrab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblTrabKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblTrab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 101, 613, 280));

        btnEditar.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/editar_estado.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 110, 100));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/off.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 90, 40));

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Solicitar Material");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 120, -1));

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Editar Estado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 120, -1));

        lblFondo1.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/fondo_rosa.png.jpg"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try{
        int f=tblTrab.getSelectedRow();
        N_boleta = tblTrab.getValueAt(f, 0).toString();
        Material = tblTrab.getValueAt(f, 1).toString();
        p_total = Double.parseDouble(tblTrab.getValueAt(f, 2).toString());
        Estado_material = tblTrab.getValueAt(f, 3).toString();
        Estado_fabricacion = tblTrab.getValueAt(f, 4).toString();
        if(f>-1){
            switch (Estado_material) {
                case "SIN ENTREGAR":
                    mensaje("No se puede concretar esta opción porque no se ha solicitado material");
                    break;
                case "SOLICITADO":
                    mensaje("No se puede concretar esta opción porque no se dispone de material");
                    break;
                default:
                    if(Estado_fabricacion.equals("TERMINADO")){
                        mensaje("No se puede editar un trabajo ya terminado");
                    }
                    else{
                        dato=String.valueOf(trab.getValueAt(tblTrab.getSelectedRow(),0));
                        dispose();
                        Trabaj_EditarReg t=new Trabaj_EditarReg();
                        t.setLocationRelativeTo(null);
                        t.setVisible(true);
                    }       break;
            }
        }
        }catch(Exception e){
            mensaje("SELECCIONE UN REGISTRO");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        try{
        int pos = tblTrab.getSelectedRow();
        Estado_material = tblTrab.getValueAt(pos, 3).toString();
        if(pos > -1){
            switch (Estado_material) {
                case "SOLICITADO":
                    mensaje("No se puede solicitar, porque ya ha sido solicitado");
                    break;
                case "ENTREGADO":
                    mensaje("No se puede solicitar, porque ya ha sido entregado el material");
                    break;
                default:
                    String usuario_solicitante = Login_trabajador.ID_usuario;
                    
                    Conexion cc = new Conexion();
                    Connection cn = cc.conexion();
            try {
                PreparedStatement pst = cn.prepareStatement("UPDATE articulo_pedido SET ENTREGA_MATERIAL = 'SOLICITADO' WHERE N_BOLETA = '"+tblTrab.getValueAt(pos, 0).toString()+"' ");
                pst.executeUpdate();
                listar_Registro_Trabajos();
                
                //CREANDO UN REGISTRO LISTA_PEDIDO
                PreparedStatement pst_lista_pedido = cn.prepareStatement("INSERT INTO lista_pedidos(ID_PEDIDO,ID_TRABAJADOR,ESTADO_ENTREGA_MATERIAL,MATERIAL,PESO_TOTAL) VALUES(?,?,?,?,?)");
                pst_lista_pedido.setString(1,tblTrab.getValueAt(pos, 0).toString());
                pst_lista_pedido.setString(2,usuario_solicitante);
                pst_lista_pedido.setString(3,"SOLICITADO");
                pst_lista_pedido.setString(4,tblTrab.getValueAt(pos, 1).toString());
                double peso_total = Double.parseDouble(tblTrab.getValueAt(pos, 2).toString());
                pst_lista_pedido.setDouble(5, peso_total);
                
                //EJECUTAR EL INSERTAR NUEVA LISTA_PEDIDO
                pst_lista_pedido.executeUpdate();
                
                mensaje("MATERIAL SOLICITADO");
                
            } catch (SQLException ex) {
                Logger.getLogger(Trabaj_RegistroTrabajos.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
            }
        }else{
            mensaje("SELECCIONE UN REGISTRO");
        }
    }catch(Exception e){
        mensaje("SELECCIONE UN REGISTRO");
    }
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void tblTrabKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTrabKeyReleased

    }//GEN-LAST:event_tblTrabKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Ventana_Trabajador vt=new Ventana_Trabajador();
        vt.setLocationRelativeTo(null);
        vt.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabaj_RegistroTrabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabaj_RegistroTrabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabaj_RegistroTrabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabaj_RegistroTrabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabaj_RegistroTrabajos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JTable tblTrab;
    // End of variables declaration//GEN-END:variables
}
