
package gui;

import Conex.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Trabaj_EditarReg extends javax.swing.JFrame {

    
    public Trabaj_EditarReg() {
        initComponents();
        
        txtBoleta.setText(Trabaj_RegistroTrabajos.N_boleta);
        txtMaterial.setText(Trabaj_RegistroTrabajos.Material);
        txtPago.setText(Trabaj_RegistroTrabajos.Estado_material);
        String Fabricacion = Trabaj_RegistroTrabajos.Estado_fabricacion;
        txtPeso.setText(""+Trabaj_RegistroTrabajos.p_total);
                        
        switch (Fabricacion) {
            case "SIN FABRICAR":
                boxFabricacion.setSelectedIndex(0);
                break;
            case "FABRICANDO":
                boxFabricacion.setSelectedIndex(1);
                break;
            default:
                boxFabricacion.setSelectedIndex(2);
                break;
        }
        
    }
    
    //arreglo_clases.Arreglo_ArticuloPedido ap=new Arreglo_ArticuloPedido();
    //Articulo_Pedido p=ap.Buscar(Trabaj_RegistroTrabajos.dato);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBoleta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JLabel();
        txtPago = new javax.swing.JLabel();
        txtPeso = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ttFabricacion = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        boxFabricacion = new javax.swing.JComboBox<>();
        lblFondo5 = new javax.swing.JLabel();
        lblFondo6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel6.setText("jLabel6");

        jLabel9.setText("jLabel9");

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nº Boleta: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 51, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel2.setText("EDITAR PEDIDO DE TRABAJO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 12, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Material: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 84, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Estado de Solicitud:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 144, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Peso Total a usar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 111, -1, -1));

        txtBoleta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBoleta.setText("jLabel10");
        getContentPane().add(txtBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 51, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Estado de Facbricación:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 182, -1, -1));

        txtMaterial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaterial.setText("jLabel11");
        getContentPane().add(txtMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 84, -1, -1));

        txtPago.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPago.setText("jLabel14");
        getContentPane().add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 144, -1, -1));

        txtPeso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPeso.setText("jLabel13");
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 111, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Guardar Cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 219, -1, -1));

        ttFabricacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(ttFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 177, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 221, -1, -1));

        boxFabricacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxFabricacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIN FABRICAR", "FABRICANDO", "TERMINADO" }));
        getContentPane().add(boxFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 177, 121, -1));

        lblFondo5.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 170, 270));

        lblFondo6.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Trabaj_RegistroTrabajos t=new Trabaj_RegistroTrabajos();
        t.setLocationRelativeTo(null);
        t.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int r = JOptionPane.showConfirmDialog(null, "¿Está seguro de editar el registro?");
        if(r==0){
            String fabricacion=boxFabricacion.getSelectedItem().toString();
            EditarRegistro(fabricacion);
            
            dispose();
            Trabaj_RegistroTrabajos t=new Trabaj_RegistroTrabajos();
            t.setLocationRelativeTo(null);
            t.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    void EditarRegistro(String fabricacion){
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
            try{
                PreparedStatement pst = cn.prepareStatement("UPDATE articulo_pedido SET FABRICACION ='"+fabricacion+"' WHERE N_BOLETA = '"+Trabaj_RegistroTrabajos.dato+"' ");
                pst.executeUpdate();
                mensaje("SE MODIFICÓ EL REGISTRO EXITOSAMENTE");
            }catch(SQLException e){
                mensaje("No se pudo conectar con la base de datos");
            }
    }
    
    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabaj_EditarReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabaj_EditarReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabaj_EditarReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabaj_EditarReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabaj_EditarReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxFabricacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFondo5;
    private javax.swing.JLabel lblFondo6;
    private javax.swing.JLabel ttFabricacion;
    private javax.swing.JLabel txtBoleta;
    private javax.swing.JLabel txtMaterial;
    private javax.swing.JLabel txtPago;
    private javax.swing.JLabel txtPeso;
    // End of variables declaration//GEN-END:variables
}
