
package gui;

import Conex.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Ventana_info_cliente extends javax.swing.JFrame {

    public Ventana_info_cliente() {
        initComponents();
        
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        
        String sql = "SELECT Nombres_cliente, Apellidos_cliente, DNI_cliente, Telefono_cliente, Correo_cliente FROM clientes WHERE DNI_cliente = '"+Login_clienteRegistrado.dni_cliente+"'";
        try{
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet resultado = pst.executeQuery();
            
            if(resultado.next()){
                Nombres = resultado.getString("Nombres_cliente");
                Apellidos = resultado.getString("Apellidos_cliente");
                Dni = resultado.getString("DNI_cliente");
                Telefono = resultado.getString("Telefono_cliente");
                Correo = resultado.getString("Correo_cliente");
                txtNombre.setText(Nombres);
                txtApellido.setText(Apellidos);
                txtDni.setText(Dni);
                txtTelef.setText(resultado.getString("Telefono_cliente"));
                txtCorreo.setText(resultado.getString("Correo_cliente"));
            }
            
        }catch(SQLException e){
            mensaje("No se puede conectar con la base de datos.");
        }
        
        Datos_Articulo_Pedido();
        
        montoTotal = Calculo(leerMaterial(),leerPeso(),leerCantidad());
        txtMontoT.setText(""+montoTotal);
        
        btnCancelarMontoR.setEnabled(false);
        btnVercomprobante.setEnabled(false);
        
        //El estado del producto debe estar como 'TERMINADO' para poder ser cancelado
        if(Login_clienteRegistrado.Estado_Fabricacion.equals("TERMINADO")){
            if(montoTotal != montoA){
                btnCancelarMontoR.setEnabled(true);
            }
        }
        
        //El monto total debe estar cancelado
        if(montoTotal == montoA){
            btnVercomprobante.setEnabled(true);
        }
        
    }
    
    
    //VARIABLES STATIC
    public static double montoTotal = 0.0;
    public static String Nombres = "";
    public static String Apellidos = "";
    public static String Dni = "";
    public static String Telefono = "";
    public static String Correo = "";
    public static double montoA=0.0;
    
    
    public String leerMaterial(){
        return txtMaterial.getText();
    }
    public double leerPeso(){
        return Double.parseDouble(txtPeso.getText());
    }
    public int leerCantidad(){
        return Integer.parseInt(txtCantidad.getText());
    }
    
    private double Calculo(String s,double peso,int cantidad){
        switch (s) {
            case "ORO":
                return peso*(3.68)*45*cantidad;
            case "PLATA":
                return peso*7*cantidad;
            default:
                return peso*4.5*cantidad;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtDni = new javax.swing.JLabel();
        txtTelef = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtArt = new javax.swing.JLabel();
        txtMed = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JLabel();
        txtPeso = new javax.swing.JLabel();
        txtMontoA = new javax.swing.JLabel();
        txtMontoT = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();
        btnCancelarMontoR = new javax.swing.JButton();
        btnVercomprobante = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblFondo10 = new javax.swing.JLabel();
        lblFondo11 = new javax.swing.JLabel();
        lblFondo12 = new javax.swing.JLabel();
        lblFondo13 = new javax.swing.JLabel();

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel1.setText("DATOS DEL CLIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel2.setText("DATOS DEL PEDIDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 30, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 13, 310));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 68, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Apellidos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 101, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("DNI:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Teléfono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 167, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Correo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtNombre.setText("jLabel8");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 68, -1, -1));

        txtApellido.setText("jLabel9");
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 101, -1, -1));

        txtDni.setText("jLabel10");
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 134, -1, -1));

        txtTelef.setText("jLabel11");
        getContentPane().add(txtTelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 167, -1, -1));

        txtCorreo.setText("jLabel12");
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("ID Artículo:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 62, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Talla/Medida:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 95, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Cantidad:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 127, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Material:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 159, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Peso:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 185, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Monto Amortiguado:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 215, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Monto total:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 248, -1, -1));

        txtArt.setText("jLabel21");
        getContentPane().add(txtArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 64, 80, -1));

        txtMed.setText("jLabel22");
        getContentPane().add(txtMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 95, 80, -1));

        txtCantidad.setText("jLabel23");
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 125, 80, -1));

        txtMaterial.setText("jLabel24");
        getContentPane().add(txtMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 155, 70, -1));

        txtPeso.setText("jLabel25");
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 185, 80, -1));

        txtMontoA.setText("jLabel26");
        getContentPane().add(txtMontoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 215, 80, -1));

        txtMontoT.setText("jLabel27");
        getContentPane().add(txtMontoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 245, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("<html>ESTADO DE FABRICACIÓN:</html>");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 280, 84, -1));

        txtEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEstado.setText("jLabel29");
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 280, 110, 20));

        btnCancelarMontoR.setText("<html><center>Cancelar monto restante</center></html>");
        btnCancelarMontoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMontoRActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarMontoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 242, 70, -1));

        btnVercomprobante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVercomprobante.setText("<html>Vizualizar comprobante de pago</hmtl>");
        btnVercomprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVercomprobanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnVercomprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 244, 90, 51));

        jButton3.setText("<  Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 319, -1, -1));

        lblFondo10.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 230, 90));

        lblFondo11.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 300));

        lblFondo12.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 300));

        lblFondo13.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        Login_clienteRegistrado lc=new Login_clienteRegistrado();
        lc.setLocationRelativeTo(null);
        lc.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnVercomprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVercomprobanteActionPerformed
        dispose();
        Client_VisualizarBoleta vb=new Client_VisualizarBoleta();
        vb.setLocationRelativeTo(null);
        vb.setVisible(true);
    }//GEN-LAST:event_btnVercomprobanteActionPerformed

    private void btnCancelarMontoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMontoRActionPerformed
        if(montoTotal != Login_clienteRegistrado.monto_amortiguado){
            dispose();
            Cliente_MontRestante mr=new Cliente_MontRestante();
            mr.setLocationRelativeTo(null);
            mr.setVisible(true);
        }else{
            mensaje("EL PEDIDO YA SE CANCELÓ");
        }
    }//GEN-LAST:event_btnCancelarMontoRActionPerformed
    
    void Datos_Articulo_Pedido(){
        
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        
        try{
            String sentencia_buscar_ArticuloPedido = ("SELECT N_BOLETA, ID_ARTICULO, MEDIDA, MATERIAL, PESO, MONTO_AMORTIGUADO, CANTIDAD, FABRICACION, ENTREGA_TRABAJO, PAGO_ESTADO, ENTREGA_MATERIAL FROM articulo_pedido WHERE N_boleta = '"+Login_clienteRegistrado.N_Boleta+"'");
            PreparedStatement pstArticulo_pedido = cn.prepareStatement(sentencia_buscar_ArticuloPedido);

            ResultSet resultado_articulopedido = pstArticulo_pedido.executeQuery();

            if(resultado_articulopedido.next()){
                txtArt.setText(resultado_articulopedido.getString("ID_ARTICULO"));
                txtMed.setText(resultado_articulopedido.getString("MEDIDA"));
                txtCantidad.setText(""+resultado_articulopedido.getInt("CANTIDAD"));
                txtMaterial.setText(resultado_articulopedido.getString("MATERIAL"));
                txtPeso.setText(""+resultado_articulopedido.getDouble("PESO"));
                txtMontoA.setText(""+resultado_articulopedido.getDouble("MONTO_AMORTIGUADO"));
                montoA = resultado_articulopedido.getDouble("MONTO_AMORTIGUADO");
                txtEstado.setText(resultado_articulopedido.getString("FABRICACION"));
            }
        }catch(SQLException e){
        }
    }
    
     void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_info_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_info_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_info_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_info_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_info_cliente().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarMontoR;
    private javax.swing.JButton btnVercomprobante;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFondo10;
    private javax.swing.JLabel lblFondo11;
    private javax.swing.JLabel lblFondo12;
    private javax.swing.JLabel lblFondo13;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtArt;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDni;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtMaterial;
    private javax.swing.JLabel txtMed;
    private javax.swing.JLabel txtMontoA;
    private javax.swing.JLabel txtMontoT;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtTelef;
    // End of variables declaration//GEN-END:variables
}
