/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 String dato=String.valueOf(catal.getValueAt(tblCatal.getSelectedRow(),1));*/
package gui;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Ventana_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Administrador
     */
    public Ventana_Administrador() {
        initComponents();
        
        btnGest_Usuarios.setIcon(setIcono("/imagenes/Gestionar_usuario.jpg", btnGest_Usuarios));
        btnGest_Usuarios.setPressedIcon(setIconoPresionado("/imagenes/Gestionar_usuario.jpg", btnGest_Usuarios, 20, 20));
        
        btnIngresos.setIcon(setIcono("/imagenes/Ingresos.png", btnIngresos));
        btnIngresos.setPressedIcon(setIconoPresionado("/imagenes/Ingresos.png", btnIngresos, 20, 20));
        
        btnList_Pedidos.setIcon(setIcono("/imagenes/Lista_pedidos.png", btnList_Pedidos));
        btnList_Pedidos.setPressedIcon(setIconoPresionado("/imagenes/Lista_pedidos.png", btnList_Pedidos, 20, 20));
        
        btnReg_Trabajos.setIcon(setIcono("/imagenes/Registro_trabajos.png", btnReg_Trabajos));
        btnReg_Trabajos.setPressedIcon(setIconoPresionado("/imagenes/Registro_trabajos.png", btnReg_Trabajos, 20, 20));
        
        btnSoporte.setIcon(setIcono("/imagenes/Soporte.png", btnSoporte));
        btnSoporte.setPressedIcon(setIconoPresionado("/imagenes/Soporte.png", btnSoporte, 20, 20));
        
        btnExportar.setIcon(setIcono("/imagenes/Exportar.png", btnExportar));
        btnExportar.setPressedIcon(setIconoPresionado("/imagenes/Exportar.png", btnExportar, 20, 20));
        
        txtNombre.setText(Login_administrador.Nombres);
        txtApellido.setText(Login_administrador.Apellidos);
        txtCorreo.setText(Login_administrador.Correo);
        txtDni.setText(Login_administrador.Dni);
        txtCelular.setText(Login_administrador.Celular);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGest_Usuarios = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnReg_Trabajos = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnSoporte = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnList_Pedidos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtDni = new javax.swing.JLabel();
        txtCelular = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFondo6 = new javax.swing.JLabel();
        lblFondo7 = new javax.swing.JLabel();
        lblFondo8 = new javax.swing.JLabel();
        lblFondo9 = new javax.swing.JLabel();
        lblFondo10 = new javax.swing.JLabel();
        lblFondo11 = new javax.swing.JLabel();
        lblFondo12 = new javax.swing.JLabel();
        lblFondo13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel1.setText("BIENVENIDO, ADMINISTRADOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 169, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Celular:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        btnGest_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGest_UsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGest_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 86, 130, 130));
        btnGest_Usuarios.getAccessibleContext().setAccessibleName("jButton2");

        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 449, 54, 14));

        btnReg_Trabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReg_TrabajosActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg_Trabajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 86, 130, 130));

        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 257, 130, 130));

        btnSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 257, 130, 130));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Gestionar Usuarios");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 222, -1, -1));

        btnList_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnList_PedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnList_Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 86, 130, 130));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Registro de trabajos");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 222, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Lista de pedidos");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 222, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Ingresos");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 393, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Soporte Técnico");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 393, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 73, -1, 360));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Datos del Usuario");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 73, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 120, 130, 23));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 169, 140, 25));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 125, 21));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 265, 110, 20));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 152, 20));

        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 257, 130, 130));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("ventas");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 416, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Información de");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 393, -1, -1));

        lblFondo6.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 270));

        lblFondo7.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 230, 270));

        lblFondo8.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 130, 270));

        lblFondo9.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 230, 200));

        lblFondo10.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 270));

        lblFondo11.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 200));

        lblFondo12.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 230, 200));

        lblFondo13.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 230, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoporteActionPerformed

        Admin_Soporte as=new Admin_Soporte();
        as.setLocationRelativeTo(null);
        as.setVisible(true);
    }//GEN-LAST:event_btnSoporteActionPerformed

    private void btnGest_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGest_UsuariosActionPerformed
        dispose();
        Gestionar_Usuarios gu=new Gestionar_Usuarios();
        gu.setLocationRelativeTo(null);
        gu.setVisible(true);
    }//GEN-LAST:event_btnGest_UsuariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Login_administrador la=new Login_administrador();
        la.setLocationRelativeTo(null);
        la.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReg_TrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReg_TrabajosActionPerformed
        dispose();
        Admin_Registro_Trabajos rt=new Admin_Registro_Trabajos();
        rt.setLocationRelativeTo(null);
        rt.setVisible(true);
    }//GEN-LAST:event_btnReg_TrabajosActionPerformed

    private void btnList_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnList_PedidosActionPerformed
        dispose();
        Admin_Lista_Pedidos p=new Admin_Lista_Pedidos();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_btnList_PedidosActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        dispose();
        Admin_Ingresos ai=new Admin_Ingresos();
        ai.setLocationRelativeTo(null);
        ai.setVisible(true);
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
         try{
            abrirarchivoTexto("Ventas.txt");
        }catch (Exception s){
            mensaje("El archivo no existe");
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    public void abrirarchivoTexto(String archivoAd){

         try {

                File objetofileA = new File (archivoAd);
                Desktop.getDesktop().open(objetofileA);

         }catch (Exception exc) {

                System.out.println(exc);
         }
    }
    
    /*/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Administrador().setVisible(true);
            }
        });
    }
    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth()-ancho;
        int height = boton.getHeight()-altura;
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        return icono;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGest_Usuarios;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnList_Pedidos;
    private javax.swing.JButton btnReg_Trabajos;
    private javax.swing.JButton btnSoporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFondo10;
    private javax.swing.JLabel lblFondo11;
    private javax.swing.JLabel lblFondo12;
    private javax.swing.JLabel lblFondo13;
    private javax.swing.JLabel lblFondo6;
    private javax.swing.JLabel lblFondo7;
    private javax.swing.JLabel lblFondo8;
    private javax.swing.JLabel lblFondo9;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtCelular;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDni;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
