/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
/**
 *
 * @author diego
 */
public class Ventana_Encargado extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Encargado
     */
    public Ventana_Encargado() {
        initComponents();
        txtNombre.setText(Login_encargado.Nombres);
        txtApellido.setText(Login_encargado.Apellidos);
        txtDni.setText(Login_encargado.Dni);
        txtCelular.setText(Login_encargado.Celular);
        txtCorreo.setText(Login_encargado.Correo);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPorEntregar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtDni = new javax.swing.JLabel();
        txtCelular = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtCorreo = new javax.swing.JLabel();
        lblFondo10 = new javax.swing.JLabel();
        lblFondo11 = new javax.swing.JLabel();
        lblFondo12 = new javax.swing.JLabel();
        lblFondo13 = new javax.swing.JLabel();
        lblFondo14 = new javax.swing.JLabel();
        lblFondo15 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 74, 130, 130));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        jLabel1.setText("BIENVENIDO ENCARGADO DE PEDIDO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Registro de Solicitudes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 209, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 81, 13, 315));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Datos del Encargado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 95, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Registro de pedidos por entregar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 379, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombres:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 144, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Apellidos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 177, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("DNI: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Celular:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 243, -1, -1));

        btnPorEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorEntregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPorEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 244, 130, 130));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Correo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 276, -1, -1));

        txtNombre.setText("jLabel11");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 144, 100, -1));

        txtApellido.setText("jLabel12");
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 177, 57, -1));

        txtDni.setText("jLabel13");
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 210, 57, -1));

        txtCelular.setText("jLabel14");
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 243, 71, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Cerrar Sesión");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 371, -1, -1));

        txtCorreo.setText("jLabel15");
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 276, 128, -1));

        lblFondo10.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 50, 250));

        lblFondo11.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 270));

        lblFondo12.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 270));

        lblFondo13.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 180));

        lblFondo14.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 230, 180));

        lblFondo15.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_complementarias/fondo_pastel.jpg"))); // NOI18N
        getContentPane().add(lblFondo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 50, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    Registro_Solicitudes rs=new Registro_Solicitudes();
    rs.setLocationRelativeTo(null);
    rs.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        Login_encargado le=new Login_encargado();
        le.setLocationRelativeTo(null);
        le.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnPorEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorEntregarActionPerformed
        dispose();
        Encarg_PorEntreg ep=new Encarg_PorEntreg();
        ep.setLocationRelativeTo(null);
        ep.setVisible(true);
    }//GEN-LAST:event_btnPorEntregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Encargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPorEntregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFondo10;
    private javax.swing.JLabel lblFondo11;
    private javax.swing.JLabel lblFondo12;
    private javax.swing.JLabel lblFondo13;
    private javax.swing.JLabel lblFondo14;
    private javax.swing.JLabel lblFondo15;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtCelular;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDni;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
