/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 String dato=String.valueOf(catal.getValueAt(tblCatal.getSelectedRow(),1));*/
package gui;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Ventana_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Administrador
     */
    public Ventana_Administrador() {
        initComponents();
        
        txtNombre.setText(Login_administrador.Nombres);
        txtApellido.setText(Login_administrador.Apellidos);
        txtCorreo.setText(Login_administrador.Correo);
        txtDni.setText(Login_administrador.Dni);
        txtCelular.setText(Login_administrador.Celular);
        
        lblGestion_user.setVisible(true);
        lblInfo.setVisible(true);
        lbl_Ingresos.setVisible(true);
        lbl_Lista_Pedido.setVisible(true);
        lbl_Soporte.setVisible(true);
        lblVenta.setVisible(true);
        lbReg_Trabajos.setVisible(true);
        
        lblGestion_user1.setVisible(false);
        lblInfo1.setVisible(false);
        lbl_Ingresos1.setVisible(false);
        lbl_Lista_Pedido1.setVisible(false);
        lbl_Soporte1.setVisible(false);
        lbReg_Trabajos1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGest_Usuarios = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnReg_Trabajos = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnSoporte = new javax.swing.JButton();
        lblGestion_user = new javax.swing.JLabel();
        btnList_Pedidos = new javax.swing.JButton();
        lbReg_Trabajos = new javax.swing.JLabel();
        lbl_Lista_Pedido = new javax.swing.JLabel();
        lbl_Ingresos = new javax.swing.JLabel();
        lbl_Soporte = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtDni = new javax.swing.JLabel();
        txtCelular = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        lblVenta = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblGestion_user1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbReg_Trabajos1 = new javax.swing.JLabel();
        lbl_Lista_Pedido1 = new javax.swing.JLabel();
        lbl_Ingresos1 = new javax.swing.JLabel();
        lbl_Soporte1 = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BIENVENIDO, ADMINISTRADOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 28, 540, -1));

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Celular:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));

        btnGest_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/gestion_user.png"))); // NOI18N
        btnGest_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGest_UsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGest_UsuariosMouseExited(evt);
            }
        });
        btnGest_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGest_UsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGest_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 130));
        btnGest_Usuarios.getAccessibleContext().setAccessibleName("jButton2");

        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 449, 54, 14));

        btnReg_Trabajos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/registro_traba.png"))); // NOI18N
        btnReg_Trabajos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReg_TrabajosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReg_TrabajosMouseExited(evt);
            }
        });
        btnReg_Trabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReg_TrabajosActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg_Trabajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 130, 130));

        btnIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/ingresos.png"))); // NOI18N
        btnIngresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresosMouseExited(evt);
            }
        });
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 130, 130));

        btnSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/soporte.png"))); // NOI18N
        btnSoporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSoporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSoporteMouseExited(evt);
            }
        });
        btnSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 130, 130));

        lblGestion_user.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblGestion_user.setText("Gestionar Usuarios");
        getContentPane().add(lblGestion_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        btnList_Pedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/lista_pedido.png"))); // NOI18N
        btnList_Pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnList_PedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnList_PedidosMouseExited(evt);
            }
        });
        btnList_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnList_PedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnList_Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 130, 130));

        lbReg_Trabajos.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lbReg_Trabajos.setForeground(new java.awt.Color(0, 0, 0));
        lbReg_Trabajos.setText("Registro de trabajos");
        getContentPane().add(lbReg_Trabajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        lbl_Lista_Pedido.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lbl_Lista_Pedido.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Lista_Pedido.setText("Lista de pedidos");
        getContentPane().add(lbl_Lista_Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        lbl_Ingresos.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lbl_Ingresos.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Ingresos.setText("Ingresos");
        getContentPane().add(lbl_Ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        lbl_Soporte.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lbl_Soporte.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Soporte.setText("Soporte Técnico");
        getContentPane().add(lbl_Soporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 10, 360));

        txtNombre.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 140, 23));

        txtApellido.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 140, 25));

        txtDni.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtDni.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 150, 21));

        txtCelular.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 130, 20));

        txtCorreo.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 180, 20));

        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/exportar.png"))); // NOI18N
        btnExportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportarMouseExited(evt);
            }
        });
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 130, 130));

        lblVenta.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblVenta.setForeground(new java.awt.Color(0, 0, 0));
        lblVenta.setText("ventas");
        getContentPane().add(lblVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        lblInfo.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblInfo.setText("Información de");
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/off.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 90, 40));

        lblGestion_user1.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblGestion_user1.setForeground(new java.awt.Color(0, 0, 0));
        lblGestion_user1.setText("<html><center>Visualizar, añadir, modificar, eliminar un usuario.");
        getContentPane().add(lblGestion_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 225, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/admin.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 150, 150));

        lbReg_Trabajos1.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lbReg_Trabajos1.setText("<html><center>Accede a una lista <p>de trabajos.");
        getContentPane().add(lbReg_Trabajos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 230, -1, -1));

        lbl_Lista_Pedido1.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lbl_Lista_Pedido1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Lista_Pedido1.setText("<html><center>Accede a un registro de <p>pedidos de materiales por <>parte de los trabajadores.");
        getContentPane().add(lbl_Lista_Pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 230, -1, -1));

        lbl_Ingresos1.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lbl_Ingresos1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Ingresos1.setText("<html><center>Muestra la lista de <p>ingresos por pedidos.");
        getContentPane().add(lbl_Ingresos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        lbl_Soporte1.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lbl_Soporte1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Soporte1.setText("<html><center>Contacto del desarrollador.");
        getContentPane().add(lbl_Soporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        lblInfo1.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblInfo1.setForeground(new java.awt.Color(0, 0, 0));
        lblInfo1.setText("<html><center>Exporta un bloc de notas <p>con los detalles de <p>cada pedido.");
        getContentPane().add(lblInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/Fondo_Ventana_Admin.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoporteActionPerformed

        Admin_Soporte as=new Admin_Soporte();
        as.setLocationRelativeTo(null);
        as.setVisible(true);
    }//GEN-LAST:event_btnSoporteActionPerformed

    private void btnGest_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGest_UsuariosActionPerformed
        dispose();
        Gestionar_Usuarios gu=new Gestionar_Usuarios();
        gu.setLocationRelativeTo(null);
        gu.setVisible(true);
    }//GEN-LAST:event_btnGest_UsuariosActionPerformed

    private void btnReg_TrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReg_TrabajosActionPerformed
        dispose();
        Admin_Registro_Trabajos rt=new Admin_Registro_Trabajos();
        rt.setLocationRelativeTo(null);
        rt.setVisible(true);
    }//GEN-LAST:event_btnReg_TrabajosActionPerformed

    private void btnList_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnList_PedidosActionPerformed
        dispose();
        Admin_Lista_Pedidos p=new Admin_Lista_Pedidos();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_btnList_PedidosActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        dispose();
        Admin_Ingresos ai=new Admin_Ingresos();
        ai.setLocationRelativeTo(null);
        ai.setVisible(true);
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
         try{
            abrirarchivoTexto("Ventas.txt");
        }catch (Exception s){
            mensaje("El archivo no existe");
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Login_administrador lt=new Login_administrador();
        lt.setLocationRelativeTo(null);
        lt.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGest_UsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGest_UsuariosMouseEntered
        lblGestion_user.setVisible(false);
        lblGestion_user1.setVisible(true);
    }//GEN-LAST:event_btnGest_UsuariosMouseEntered

    private void btnGest_UsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGest_UsuariosMouseExited
        lblGestion_user1.setVisible(false);
        lblGestion_user.setVisible(true);
    }//GEN-LAST:event_btnGest_UsuariosMouseExited

    private void btnReg_TrabajosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReg_TrabajosMouseEntered
        lbReg_Trabajos.setVisible(false);
        lbReg_Trabajos1.setVisible(true);
    }//GEN-LAST:event_btnReg_TrabajosMouseEntered

    private void btnReg_TrabajosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReg_TrabajosMouseExited
        lbReg_Trabajos.setVisible(true);
        lbReg_Trabajos1.setVisible(false);
    }//GEN-LAST:event_btnReg_TrabajosMouseExited

    private void btnList_PedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnList_PedidosMouseEntered
        lbl_Lista_Pedido.setVisible(false);
        lbl_Lista_Pedido1.setVisible(true);
    }//GEN-LAST:event_btnList_PedidosMouseEntered

    private void btnList_PedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnList_PedidosMouseExited
        lbl_Lista_Pedido.setVisible(true);
        lbl_Lista_Pedido1.setVisible(false);
    }//GEN-LAST:event_btnList_PedidosMouseExited

    private void btnIngresosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresosMouseEntered
        lbl_Ingresos.setVisible(false);
        lbl_Ingresos1.setVisible(true);
    }//GEN-LAST:event_btnIngresosMouseEntered

    private void btnIngresosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresosMouseExited
        lbl_Ingresos.setVisible(true);
        lbl_Ingresos1.setVisible(false);
    }//GEN-LAST:event_btnIngresosMouseExited

    private void btnSoporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporteMouseEntered
        lbl_Soporte.setVisible(false);
        lbl_Soporte1.setVisible(true);
    }//GEN-LAST:event_btnSoporteMouseEntered

    private void btnSoporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporteMouseExited
        lbl_Soporte.setVisible(true);
        lbl_Soporte1.setVisible(false);
    }//GEN-LAST:event_btnSoporteMouseExited

    private void btnExportarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseEntered
        lblVenta.setVisible(false);
        lblInfo.setVisible(false);
        lblInfo1.setVisible(true);
    }//GEN-LAST:event_btnExportarMouseEntered

    private void btnExportarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseExited
        lblVenta.setVisible(true);
        lblInfo.setVisible(true);
        lblInfo1.setVisible(false);
    }//GEN-LAST:event_btnExportarMouseExited

    void mensaje(String s) {
	JOptionPane.showMessageDialog(this, s);
    }
    public void abrirarchivoTexto(String archivoAd){

         try {

                File objetofileA = new File (archivoAd);
                Desktop.getDesktop().open(objetofileA);
                

         }catch (Exception exc) {

                System.out.println(exc);
         }
    }
    
    /*/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Administrador().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGest_Usuarios;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnList_Pedidos;
    private javax.swing.JButton btnReg_Trabajos;
    private javax.swing.JButton btnSoporte;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbReg_Trabajos;
    private javax.swing.JLabel lbReg_Trabajos1;
    private javax.swing.JLabel lblGestion_user;
    private javax.swing.JLabel lblGestion_user1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblVenta;
    private javax.swing.JLabel lbl_Ingresos;
    private javax.swing.JLabel lbl_Ingresos1;
    private javax.swing.JLabel lbl_Lista_Pedido;
    private javax.swing.JLabel lbl_Lista_Pedido1;
    private javax.swing.JLabel lbl_Soporte;
    private javax.swing.JLabel lbl_Soporte1;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtCelular;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDni;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
