/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author SAMIR
 */
public class Ventana_clientes extends javax.swing.JFrame {

    /**
     * Creates new form Login_clientes
     */
    public Ventana_clientes() {
        initComponents();
        
        btnRegistrado.setIcon(setIcono("/imagenes/cliente_registrado.png", btnRegistrado));
        btnRegistrado.setPressedIcon(setIconoPresionado("/imagenes/cliente_registrado.png", btnRegistrado, 20, 20));
        
        btnInvitado.setIcon(setIcono("/imagenes/invitado.png", btnInvitado));
        btnInvitado.setPressedIcon(setIconoPresionado("/imagenes/invitado.png", btnInvitado, 20, 20));
        
        btnRetro.setIcon(setIcono("/imagenes_interfaces/retroceder.png", btnRetro));
        btnRetro.setPressedIcon(setIconoPresionado("/imagenes_interfaces/retroceder.png", btnRetro, 9, 9));
        
        ImageIcon imagen = new ImageIcon("src/imagenes_interfaces/senialar.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblSenialar.getWidth(), lblSenialar.getHeight(), Image.SCALE_DEFAULT));
        lblSenialar.setIcon(icono);
        
        lblTextoCliente_invitado.setVisible(false);
        lblTextoCliente_registrado.setVisible(false);
        lblSenialar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInvitado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrado = new javax.swing.JButton();
        btnRetro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblTextoCliente_invitado = new javax.swing.JLabel();
        lblTextoCliente_registrado = new javax.swing.JLabel();
        lblSenialar = new javax.swing.JLabel();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel1.setText("Seleccionar Opción de Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, -1));

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel2.setText("Seleccione de que manera desea ingresar al sistema:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, -1));

        btnInvitado.setContentAreaFilled(false);
        btnInvitado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvitadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvitadoMouseExited(evt);
            }
        });
        btnInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInvitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 124, 119));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel3.setText("Iniciar sesión");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel4.setText("Ingresar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        btnRegistrado.setContentAreaFilled(false);
        btnRegistrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistradoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistradoMouseExited(evt);
            }
        });
        btnRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistradoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 124, 119));

        btnRetro.setContentAreaFilled(false);
        btnRetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 50));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel5.setText("como invitado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        lblTextoCliente_invitado.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblTextoCliente_invitado.setText("<html> Seleccionando está opción visualizará nuestro <p>catálogo de artículos.");
        getContentPane().add(lblTextoCliente_invitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 210, 60));

        lblTextoCliente_registrado.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        lblTextoCliente_registrado.setText("<html> Seleccione esta opción si usted <p>ha realizado una solicitud de fabricación de un artículo.");
        getContentPane().add(lblTextoCliente_registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 200, 60));
        getContentPane().add(lblSenialar, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 290, 50, 40));

        lblFondo1.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_interfaces/color_ventanas.jpg"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistradoActionPerformed
        dispose();
        Login_clienteRegistrado lcr = new Login_clienteRegistrado();
        lcr.setLocationRelativeTo(null);
        lcr.setVisible(true);
    }//GEN-LAST:event_btnRegistradoActionPerformed

    private void btnInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvitadoActionPerformed
        dispose();
        Inicio_invitado ii = new Inicio_invitado();
        ii.setLocationRelativeTo(null);
        ii.setVisible(true);
    }//GEN-LAST:event_btnInvitadoActionPerformed

    private void btnRetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetroActionPerformed
        dispose();
        Ventana_principal vp = new Ventana_principal(this, true);
        vp.setLocationRelativeTo(null);
        vp.setVisible(true);
    }//GEN-LAST:event_btnRetroActionPerformed

    private void btnRegistradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistradoMouseEntered
        lblTextoCliente_registrado.setVisible(true);
        lblSenialar.setVisible(true);
    }//GEN-LAST:event_btnRegistradoMouseEntered

    private void btnInvitadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvitadoMouseEntered
        lblTextoCliente_invitado.setVisible(true);
        lblSenialar.setVisible(true);
    }//GEN-LAST:event_btnInvitadoMouseEntered

    private void btnRegistradoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistradoMouseExited
        lblTextoCliente_registrado.setVisible(false);
        lblSenialar.setVisible(false);
    }//GEN-LAST:event_btnRegistradoMouseExited

    private void btnInvitadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvitadoMouseExited
        lblTextoCliente_invitado.setVisible(false);
        lblSenialar.setVisible(false);
    }//GEN-LAST:event_btnInvitadoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_clientes().setVisible(true);
            }
        });
    }

    public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth()-ancho;
        int height = boton.getHeight()-altura;
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        return icono;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInvitado;
    private javax.swing.JButton btnRegistrado;
    private javax.swing.JButton btnRetro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblSenialar;
    private javax.swing.JLabel lblTextoCliente_invitado;
    private javax.swing.JLabel lblTextoCliente_registrado;
    // End of variables declaration//GEN-END:variables
}
